import type { Article } from "./types";

type DanishCopy = { keyword: string; answer: string; facts: string; steps: string[]; caution: string };

const copy: Record<string, DanishCopy> = {
  "big-ambitions-market-insider": { keyword:"Big Ambitions Market Insider", answer:"Brug Market Insider til at sammenligne efterspørgsel og konkurrence i det relevante distrikt, før du vælger virksomhed, lokale eller produktsortiment.", facts:"Markedsdata er et beslutningsværktøj, ikke en garanti for overskud. Husleje, kundekapacitet, priser, løn og forsyning påvirker stadig resultatet.", steps:["Vælg det distrikt, hvor virksomheden skal ligge.","Sammenlign udækket efterspørgsel og eksisterende konkurrenter.","Vurder lokaler og startomkostninger sammen med markedet.","Kontrollér data igen efter ændringer i konkurrence eller sortiment."], caution:"Tal og balancering kan ændre sig mellem versioner og forskellige spiltyper." },
  "big-ambitions-warehouse-setup": { keyword:"Big Ambitions opsætning af lager", answer:"Et lager skal have plads, leveringskøretøj, de nødvendige medarbejdere og korrekte forbindelser til importører og butikker, før forsyningskæden kan køre automatisk.", facts:"Lageret forbinder indkøb med distribution. En bygning alene flytter ingen varer, hvis kontrakter, ruter, chauffør eller lagerarbejde mangler.", steps:["Vælg et lager med passende køretøjspladser.","Indret arbejdspladser og lagerkapacitet.","Tilknyt importør og de butikker, der skal forsynes.","Tildel køretøj, rute og kvalificerede medarbejdere.","Kontrollér beholdning og leveringer over flere dage."], caution:"Grænser, jobtitler og leveringstider skal kontrolleres i den aktuelle version." },
  "big-ambitions-purchasing-agent": { keyword:"Big Ambitions indkøbsagent", answer:"En indkøbsagent håndterer importørkontrakter fra hovedkontoret. Medarbejderen skal have den rette arbejdsplads og kompetence, og kontrakten skal forbindes til det korrekte lager.", facts:"Indkøb og fysisk levering er forskellige led: agenten organiserer kontrakten, mens lager, køretøj og logistikpersonale får varerne videre til butikkerne.", steps:["Opret en egnet arbejdsplads på hovedkontoret.","Ansæt og tildel en kvalificeret indkøbsagent.","Vælg importør og varer i den aktuelle grænseflade.","Forbind kontrakten til det ønskede lager.","Følg lagerbeholdning og udgifter efter aktivering."], caution:"Kompetencekrav, kontraktgrænser og menupunkter kan ændres med opdateringer." },
  "big-ambitions-logistics-manager": { keyword:"Big Ambitions logistikchef", answer:"Logistikchefen styrer leveringsruter fra lageret til virksomhederne. Ruten kræver et egnet køretøj, tilstrækkelig kapacitet og en medarbejderopsætning, der faktisk kan gennemføre leveringen.", facts:"En korrekt importørkontrakt fylder lageret, men varer når ikke automatisk butikkerne uden en fungerende distributionsrute.", steps:["Kontrollér at lageret modtager de ønskede varer.","Ansæt og placér den nødvendige logistikmedarbejder.","Vælg køretøj og tilknyt målbutikker.","Indstil varevalg og leveringsmængder.","Overvåg tomme hylder og justér kapacitet eller hyppighed."], caution:"Leveringstider, rutegrænser og Smart Delivery-adfærd afhænger af den aktuelle version." },
  "big-ambitions-guide": { keyword:"Big Ambitions guide", answer:"Den sikreste start er at dække figurens behov, følge de tidlige mål, undersøge lokal efterspørgsel og åbne en lille virksomhed uden at bruge hele kontantbeholdningen.", facts:"Spillet fører dig fra det første job til lejede lokaler, udstyr, lager, medarbejdere, logistik, hovedkontor, ejendomme og investeringer. Sundhed og trivsel skal styres sammen med økonomien.", steps:["Få styr på søvn, mad, sundhed og bolig.","Følg introduktionsmålene, før du foretager risikable køb.","Brug Market Insider til at sammenligne efterspørgsel og konkurrence.","Automatisér den første butik, før du åbner den næste."], caution:"Menupunkter, priser og balance kan ændre sig. Kontrollér altid den aktuelle F1-hjælp, BizMan og Market Insider." },
  "big-ambitions-best-starting-business": { keyword:"Big Ambitions bedste startvirksomhed", answer:"Der findes ikke én bedste startvirksomhed i alle spil. Vælg en billig virksomhed med høj udækket efterspørgsel, overskuelig konkurrence og penge til overs efter åbningen.", facts:"Gavebutik, fastfood og kaffe nævnes ofte som tilgængelige valg, mens smykker, tøj og elektronik kan kræve mere kapital. Det lokale marked afgør, hvad der fungerer.", steps:["Kontrollér efterspørgslen i Market Insider.","Sammenlign konkurrenter, husleje og kundekapacitet.","Medregn inventar, startlager og lønninger.","Behold en kontant reserve til den daglige drift."], caution:"Kopiér ikke en gammel rangliste uden at kontrollere dit eget distrikt og den aktuelle spilversion." },
  "big-ambitions-best-investment": { keyword:"Big Ambitions bedste investeringsfond", answer:"Ingen fond er altid bedst. Sammenlign bankens aktuelle risikoniveauer, behold driftskapital kontant, og overvej først at investere mere i en virksomhed, der allerede giver stabilt overskud.", facts:"Spillet har investeringsfonde, ejendomme og virksomhedsudvidelse som forskellige anvendelser af kapital. Ingen primær kilde lover en permanent vinder eller et garanteret afkast.", steps:["Hold penge tilbage til husleje, løn og varer.","Sammenlign fondenes viste risiko i banken.","Vurder fonden mod geninvestering i en dokumenteret butik.","Bedøm resultatet over flere perioder, ikke én dag."], caution:"Fondsnavne, risiko og afkast kan ændres mellem versioner. Høj risiko garanterer ikke det bedste resultat." },
  "big-ambitions-where-to-buy-truck": { keyword:"Big Ambitions hvor køber man en lastbil", answer:"Køb en leveringslastbil hos en bilforhandler, som vises på kortet. Sørg først for, at lageret har en egnet plads, og at ruten og kapaciteten retfærdiggør købet.", facts:"Steam-beskrivelsen bekræfter, at leveringskøretøjer købes hos en forhandler og bruges sammen med lager- og logistiksystemerne.", steps:["Find bilforhandleren på det aktuelle kort.","Kontrollér køretøjets kapacitet.","Sørg for en brugbar plads ved lageret.","Tildel rute og personale, når lagerforbindelsen virker."], caution:"Lagerbeholdning, pris og kortnavne kan ændre sig. Brug kortet og F1-hjælpen frem for gamle adresser." },
  "big-ambitions-where-to-buy-bathroom-stall": { keyword:"Big Ambitions hvor køber man en toiletkabine", answer:"Køb Bathroom Stall hos Essentials Appliances. Søg efter den præcise engelske genstandsbetegnelse i F1-hjælpen, så du ikke forveksler den med et almindeligt toilet.", facts:"En udvikler har i Steam-diskussioner bekræftet, at Essentials Appliances sælger Bathroom Stall. Butikkens lager kan ses via kortets forstørrelsesglas.", steps:["Bekræft kravet i BizMan.","Søg efter Bathroom Stall i F1-hjælpen.","Find Essentials Appliances på kortet.","Køb, placér og kontrollér derefter kravet i BizMan."], caution:"Den aktuelle pris, lagerstatus og eventuelle forudsætninger skal kontrolleres i spillet." },
  "big-ambitions-how-to-take-courses": { keyword:"Big Ambitions sådan tager du kurser", answer:"En sikker fremgangsmåde for kurser i version 1.0 er ikke officielt bekræftet. Kontrollér aktuelle mål, F1-hjælpen og en eventuel skolegrænseflade i dit spil.", facts:"Ældre diskussioner forbinder kurser med skole, HR og kontorledelse, men de dokumenterer ikke nødvendigvis den nuværende arbejdsgang.", steps:["Læs dine aktive mål.","Søg efter course, school, management og HR i F1.","Kontrollér tid, pris, krav og belønning før betaling.","Betragt en manglende grænseflade som tegn på forældet vejledning."], caution:"Placering, åbningstid, pris og oplåsning af kurser afventer bekræftelse." },
  "big-ambitions-how-to-get-diploma": { keyword:"Big Ambitions sådan får du et diplom", answer:"Der findes ingen sikker officiel bekræftelse på, at et diplom er en særskilt genstand eller belønning i version 1.0. Kontrollér F1-hjælp, mål, skole og præstationer.", facts:"Søgeresultaterne blander ældre spilleropslag med uvedkommende uddannelsessider. Ordet kan være et gammelt mål eller spillernes egen betegnelse.", steps:["Søg efter Diploma og kursusord i F1.","Gennemgå aktuelle uddannelsesmål.","Kontrollér belønningsteksten i skolegrænsefladen.","Brug det nuværende navn, hvis Diploma ikke findes."], caution:"Krav, pris, varighed og belønning afventer bekræftelse; siden opfinder ikke en løsning." },
  "big-ambitions-how-to-upload-images": { keyword:"Big Ambitions sådan uploader du billeder", answer:"Læg en PNG-fil i Windows-mappen CustomIcons, opdatér listen og vælg billedet i virksomhedens tilpasning i BizMan.", facts:"Forum- og Steam-opslag beskriver stien AppData/LocalLow/Hovgaard Games/Big Ambitions/CustomIcons. Logoer og billeder til skilte kan have forskellige regler.", steps:["Lav en tydelig PNG med god kontrast.","Læg filen direkte i CustomIcons-mappen.","Åbn virksomhedens logotilpasning i BizMan.","Opdatér listen, vælg billedet og gem."], caution:"Ældre opslag er uenige om 512 × 512 og 1024 × 1024. Den bedste størrelse i version 1.0 skal bekræftes i spillet." },
  "big-ambitions-similar-games": { keyword:"Spil som Big Ambitions", answer:"Det bedste alternativ afhænger af, om du vil bevare virksomhedsledelse, åben livssimulation, aktiv butiksdrift eller kontor- og medarbejdersystemer.", facts:"Startup Company, Software Inc., Capitalism, SAELIG og The Guild nævnes ofte, men ingen af dem kopierer alle dele af Big Ambitions.", steps:["Vælg om forretningsdybde eller figurliv er vigtigst.","Sammenlign personale, produktion og logistik.","Kontrollér officielle platforme og spiltilstande.","Notér også hvilke funktioner hvert alternativ mangler."], caution:"En anbefaling fra fællesskabet garanterer ikke identiske mekanikker eller aktuel tilgængelighed." },
  "big-ambitions-multiplayer-alternatives": { keyword:"Big Ambitions multiplayer-alternativer", answer:"Big Ambitions er officielt et enkeltspillerspil. Hvis du kræver co-op eller konkurrence, skal du vælge et andet spil med bekræftet multiplayer.", facts:"Et uofficielt Big Ambitions Online-projekt er omtalt af fællesskabet, men det er ikke tilknyttet Hovgaard Games og er ikke officiel onlineunderstøttelse.", steps:["Vælg mellem samarbejde og økonomisk konkurrence.","Kontrollér multiplayer på spillets officielle butiksside.","Undersøg spillerantal, hosting og delt progression.","Adskil indbygget multiplayer fra tredjepartsmods."], caution:"Kompatibilitet og sikkerhed for uofficielle projekter afventer bekræftelse." },
  "big-ambitions-romance-alternatives": { keyword:"Big Ambitions alternativer med romantik", answer:"Big Ambitions markedsfører ikke et dybt romantiksystem. Sammenlign i stedet livssimulationer, hvor forhold og romantik bekræftes i den officielle beskrivelse.", facts:"Den officielle beskrivelse fokuserer på virksomheder, investeringer, ejendomme, sundhed og trivsel frem for dating.", steps:["Bekræft at romantik har reel progression.","Sammenlign dybden i virksomhedsdriften.","Kontrollér figurliv og platforme.","Vælg den balance mellem forhold og ledelse, du ønsker."], caution:"NPC-samtaler eller bryllupsdekoration er ikke i sig selv et fuldt romantiksystem." },
  "big-ambitions-1-0-release-date": { keyword:"Big Ambitions 1.0 udgivelsesdato", answer:"Big Ambitions version 1.0 udkom den 28. august 2026. Spillet kom i Steam Early Access den 10. marts 2023.", facts:"De officielle kilder skelner mellem Early Access og den fulde 1.0-udgivelse. Datoen i 2023 må derfor ikke kaldes den endelige udgivelse.", steps:["Brug 10. marts 2023 som Early Access-dato.","Brug 28. august 2026 som 1.0-dato.","Læs Steam News for den officielle ændringsliste.","Adskil lanceringsindhold fra senere opdateringer."], caution:"En 1.0-udgivelse bekræfter ikke automatisk konsol- eller mobilversioner." },
  "big-ambitions-next-update": { keyword:"Big Ambitions næste opdatering", answer:"Den næste Big Ambitions-opdatering har ingen bekræftet dato i det undersøgte materiale. Brug kun roadmap, Steam News og direkte udviklermeddelelser som bekræftelse.", facts:"Efter 1.0-udgivelsen kan ældre roadmap-opslag let blive misforstået. Allerede udgivet indhold, udaterede planer og spillerønsker skal holdes adskilt.", steps:["Kontrollér det officielle roadmap.","Sammenlign med det nyeste Steam News-opslag.","Kræv en dato direkte fra Hovgaard Games.","Erstat gamle oplysninger, når en ny officiel meddelelse kommer."], caution:"Ønskelister, mods og spekulationer er ikke officielle planer." },
  "big-ambitions-patch-notes": { keyword:"Big Ambitions patch notes", answer:"Brug Steam News og udviklerens officielle opslag som hovedkilde til patch notes. Match altid ændringer med versionsnummer og dato.", facts:"Ældre Early Access-noter er historiske; version 1.0 og senere opdateringer er mest relevante nu. Spillerberetninger skal markeres separat.", steps:["Notér den præcise version og dato.","Adskil funktioner, balance og fejlrettelser.","Tilføj kun kendte problemer med officiel bekræftelse.","Link til den originale officielle meddelelse."], caution:"Et problem rapporteret af en spiller er ikke automatisk et officielt kendt problem." },
  "big-ambitions-mobile": { keyword:"Big Ambitions til mobil", answer:"Der er ingen bekræftet officiel Android- eller iOS-version af Big Ambitions. Steam viser Windows og macOS, mens mobiludgivelse og dato afventer bekræftelse.", facts:"Hverken den officielle hjemmeside eller Steam har et formelt produktlink til App Store eller Google Play.", steps:["Kontrollér Hovgaard Games og den officielle hjemmeside.","Kræv et verificeret App Store- eller Google Play-link.","Adskil Steam-streaming fra en indbygget mobilapp.","Undgå APK-filer fra ukendte sider."], caution:"Mobilpris, funktioner og udgivelsesdato er ikke bekræftet." },
  "big-ambitions-mods": { keyword:"Big Ambitions mods", answer:"Brug Steam Workshop til Big Ambitions-mods, kontrollér versionskompatibilitet, og sikkerhedskopiér dit spil, før du aktiverer ændringer.", facts:"Mods ændrer spillets funktioner, mens blueprints gemmer genanvendelige indretninger. De to typer indhold skal ikke behandles som det samme.", steps:["Åbn den officielle Steam Workshop.","Læs krav, afhængigheder og versionsnoter.","Aktivér én ændring ad gangen.","Deaktivér alle mods ved nedbrud og test dem enkeltvis."], caution:"Undgå ukendte eksekverbare downloads, og kontrollér kompatibilitet efter hver spilopdatering." },
  "big-ambitions-blueprints": { keyword:"Big Ambitions blueprints", answer:"Blueprints er genanvendelige rumindretninger, ikke kode-mods. De skal passe til ejendomstype, bygningskode og tilgængelig størrelse.", facts:"Workshop-abonnementet skal synkroniseres med biblioteket i spillet, hvorefter den rette indretningsvirksomhed kan anvende layoutet.", steps:["Abonnér på et troværdigt Workshop-layout.","Synkronisér det med biblioteket i spillet.","Kontrollér bygningstype, kode og størrelse.","Brug den korrekte indretningsvirksomhed."], caution:"Ældre blueprints kan kræve forældede versioner eller mods. Sikkerhedskopiér spillet først." },
  "big-ambitions-review": { keyword:"Big Ambitions anmeldelse", answer:"Big Ambitions passer bedst til spillere, der vil kombinere detaljeret virksomhedsledelse med direkte bevægelse gennem byen og gradvis automatisering.", facts:"Steam viste en meget positiv engelsksproget anmeldelsesoversigt ved kontrollen 31. august 2026, men antal og procent ændrer sig løbende.", steps:["Vurder dybden i ledelse og automatisering.","Afgør om byture føles levende eller gentagende.","Overvej hvor meget personale- og logistikstyring du ønsker.","Læs aktuelle ydelses- og patchrapporter."], caution:"Kontrollér altid det aktuelle anmeldelsestal direkte på Steam." },
  "big-ambitions-crashes": { keyword:"Big Ambitions går ned", answer:"Ved nedbrud bør du først kontrollere systemkrav, opdatere system og grafikdriver, verificere Steam-filer og teste uden mods.", facts:"Spillere rapporterer især startproblemer og lang shader-kompilering. Startparametre med lav kvalitet kan bruges som diagnose, men er ikke en garanteret officiel løsning.", steps:["Sammenlign pc'en med Steam-kravene.","Opdatér grafikdriver og operativsystem.","Verificér spilfiler via Steam.","Test uden mods og med en sikkerhedskopieret gemmefil.","Indsaml log, version og hardware til support."], caution:"Sikkerhedskopiér data, før du ændrer eller fjerner konfiguration og cache." },
  "big-ambitions-water-cooler": { keyword:"Big Ambitions vandkøler", answer:"En officiel placering, sælger eller pris for en Water Cooler kunne ikke bekræftes. Kontrollér den præcise genstandsbetegnelse i F1 og kravet i BizMan.", facts:"Officielle kilder bekræfter, at virksomheder bruger møbler og udstyr, men ikke en permanent sælger eller pris for netop denne genstand.", steps:["Læs det præcise krav i BizMan.","Søg efter Water Cooler og lignende ord i F1.","Brug genstandens henvisning til en eventuel sælger.","Kontrollér den aktuelle butiksbeholdning."], caution:"Tilgængelighed, pris, størrelse og effekt afventer bekræftelse." },
  "big-ambitions-ai-music": { keyword:"Big Ambitions AI-musik", answer:"Der findes ingen bekræftet officiel udtalelse om, at Big Ambitions bruger AI-genereret musik. Licensering fortæller ikke i sig selv, hvordan et musiknummer blev skabt.", facts:"En repræsentant for Hovgaard Games har oplyst, at radiojinglerne er originale, og at musikken er licenseret til spil og streaming.", steps:["Adskil licens fra produktionsmetode.","Kontrollér krediteringer og soundtrack-oplysninger.","Søg en direkte udtalelse fra udvikler eller kunstner.","Brug ikke detektionsværktøjer som endeligt bevis."], caution:"Om et bestemt nummer anvender generativ AI, afventer bekræftelse." },
  "big-ambitions-music": { keyword:"Big Ambitions musik", answer:"Big Ambitions har licenseret musik, originale radiojingler og en separat station til lokale MP3-filer.", facts:"Udviklersvar bekræfter, at kompatible MP3-filer afspilles på deres egen station, når de lægges direkte i den valgte musikmappe.", steps:["Find musikmappen under Options og Audio.","Læg MP3-filer direkte i mappen.","Tænd en radio eller kompatibel højttaler i spillet.","Vælg den lokale station frem for standardsoundtracket."], caution:"Den fulde aktuelle trackliste og rettighedshaver for hvert nummer afventer bekræftelse." },
  "big-ambitions-life-sim-game": { keyword:"Big Ambitions som livssimulation", answer:"Big Ambitions er en virksomhedssimulation med livssimulationssystemer, ikke en ren hverdagssimulator.", facts:"Spilleren styrer søvn, mad, sundhed, trivsel, bolig, transport og indkøb samtidig med butikker, kontorer, logistik, ejendomme og investeringer.", steps:["Forvent at virksomhedsvækst er hovedforløbet.","Styr personlige behov, fordi de påvirker driften.","Brug bolig, transport og bytjenester som funktionelle systemer.","Sammenlign romantik og familieliv separat med rene livsspil."], caution:"Mærkatet Life Sim bekræfter ikke dyb romantik, familie, aldring eller multiplayer." },
  "big-ambitions-uniform": { keyword:"Big Ambitions medarbejderuniformer", answer:"Big Ambitions understøtter uniformer til medarbejdere, men den aktuelle tildeling og de mulige farver skal kontrolleres i medarbejderstyringen.", facts:"Det officielle forum markerer uniformforslaget som implementeret i Beta 8, og senere Early Access-opslag omtaler flere tøjvalg.", steps:["Åbn BizMan og vælg virksomhed eller medarbejdergruppe.","Find den aktuelle uniform- eller tøjindstilling.","Vælg muligheder, som rollen understøtter.","Kontrollér resultatet under en aktiv vagt."], caution:"Den præcise 1.0-menu, komplette tøjliste og logoer på uniformer afventer bekræftelse." },
  "big-ambitions-multiplayer": { keyword:"Big Ambitions multiplayer", answer:"Big Ambitions har ikke officiel multiplayer eller co-op; Steam viser spillet som enkeltspiller.", facts:"Ældre udviklerkommentarer omtaler multiplayer som en mulig idé efter udgivelsen, men de er hverken en køreplan, en bekræftet funktion eller en dato.", steps:["Kontrollér den aktuelle Steam-funktionsliste.","Læs roadmap og de nyeste Steam News.","Kræv en direkte meddelelse fra Hovgaard Games.","Adskil officiel støtte fra tredjepartsprojekter."], caution:"Spillerantal, netværksmodel og udgivelsesdato for multiplayer afventer bekræftelse." },
  "big-ambitions-customer-capacity": { keyword:"Big Ambitions kundekapacitet", answer:"Kundekapaciteten begrænser, hvor mange kunder et lokale kan håndtere. Match lokalets trafik med kasser, udstyr og bemanding, før du betaler for større kapacitet.", facts:"Et større lokale giver ikke automatisk højere fortjeneste. Flaskehalse i service, lager eller personale kan stadig holde salget nede.", steps:["Kontrollér lokalets viste kapacitet.","Find flaskehalse i kasser og serviceudstyr.","Planlæg nok medarbejdere til åbningstiden.","Udvid først, når efterspørgslen faktisk udnyttes."], caution:"Præcise kapacitets- og kundetal kan ændre sig med balanceopdateringer." },
  "big-ambitions-employee-scheduling": { keyword:"Big Ambitions medarbejderplan", answer:"Lav vagtplanen efter åbningstid, medarbejdernes kompetencer og hvile. Sørg for dækning af hver nødvendig funktion uden unødvendige løntimer.", facts:"Automatisering kræver, at de rigtige roller er bemandet, og at medarbejdernes tilfredshed og arbejdstid kan opretholdes.", steps:["Fastlæg åbningstiderne.","Tildel kvalificerede medarbejdere til hver rolle.","Undgå overlap uden et konkret kapacitetsbehov.","Kontrollér fravær, tilfredshed og lønomkostning."], caution:"Arbejdstidsgrænser og kompetencekrav skal kontrolleres i den aktuelle BizMan-visning." },
  "big-ambitions-product-pricing": { keyword:"Big Ambitions produktpriser", answer:"Sæt priser ud fra marked, konkurrence og kundernes reaktion, og ændr dem i små trin. Den højeste mulige pris er sjældent den bedste langsigtede pris.", facts:"Efterspørgsel, salgsvolumen og kundetilfredshed hænger sammen. Sammenlign indtjening over flere åbne dage frem for ét øjebliksbillede.", steps:["Kontrollér marked og konkurrenter.","Beregn vareforbrug og bruttoavance.","Justér én produktgruppe ad gangen.","Følg salg og tilfredshed over flere dage."], caution:"Ingen universel prisprocent passer til alle distrikter, produkter og versioner." },
  "big-ambitions-office-requirements": { keyword:"Big Ambitions kontorkrav", answer:"Kontrollér kontorets præcise krav i BizMan, før du køber udstyr. Rum, arbejdsstationer og medarbejderroller skal passe til den funktion, kontoret skal udføre.", facts:"Hovedkontor- og administrationsfunktioner knytter medarbejdere og udstyr til virksomhedens automatisering og logistik.", steps:["Læs alle manglende krav i BizMan.","Kontrollér genstandsnavne i F1-hjælpen.","Køb kun udstyr til den planlagte rolle.","Placér, bemand og kontrollér derefter status igen."], caution:"Genstandsnavne, antal og oplåsningskrav kan ændre sig mellem versioner." },
  "big-ambitions-ps5": { keyword:"Big Ambitions til PS5", answer:"En officiel PS5-version og udgivelsesdato er ikke bekræftet. De aktuelt bekræftede Steam-platforme er Windows og macOS.", facts:"En fuld pc-udgivelse betyder ikke automatisk, at der findes en konsolport. Brug kun en officiel butiksside eller udviklermeddelelse som bevis.", steps:["Kontrollér den officielle hjemmeside og roadmap.","Søg efter en verificeret PlayStation Store-side.","Læs de nyeste Steam News og udvikleropslag.","Ignorér datoer uden en primær kilde."], caution:"PS5-pris, funktioner, cross-save og udgivelsesdato afventer bekræftelse." },
};

function description(keyword: string, answer: string) {
  const text = `${keyword}: ${answer} Guiden bygger på kontrollerede kilder og markerer tydeligt oplysninger, der endnu ikke er bekræftet.`;
  if (text.length <= 160) return text.padEnd(140, " ").trimEnd();
  const cut = text.slice(0, 159);
  return `${cut.slice(0, cut.lastIndexOf(" "))}.`;
}

function title(keyword: string) {
  let value = `${keyword} – dansk guide`;
  if (value.length < 40) value += " til spillere";
  return value.length <= 60 ? value : `${keyword.slice(0, 43)} – guide`;
}

export function localizeDanishArticle(article: Article): Article {
  const item = copy[article.slug];
  if (!item) throw new Error(`Manglende dansk tekst til ${article.slug}`);
  return {
    ...article,
    locale: "da",
    keyword: item.keyword,
    title: title(item.keyword),
    description: description(item.keyword, item.answer),
    summary: item.answer,
    answer: item.answer,
    sections: [
      { heading: "Det skal du vide", paragraphs: [item.facts] },
      { heading: "Trin for trin", paragraphs: [], bullets: item.steps },
      { heading: "Version og begrænsninger", paragraphs: [item.caution] },
      { heading: "Dit næste skridt", paragraphs: [item.answer] },
    ],
    sources: article.sources.map((source) => {
      const href = source.href;
      const label = href.includes("bigambitionsgame.com/roadmap") ? "Officielt roadmap"
        : href.includes("bigambitionsgame.com") ? "Officiel Big Ambitions-hjemmeside"
        : href.includes("store.steampowered.com/news") ? "Officielle Steam-nyheder"
        : href.includes("store.steampowered.com/app") ? "Big Ambitions på Steam"
        : href.includes("help.steampowered.com") ? "Steam Support"
        : href.includes("steamcommunity.com/workshop") ? "Steam Workshop"
        : href.includes("steamcommunity.com/app") ? "Diskussion i Steam-fællesskabet"
        : href.includes("forum.bigambitionsgame.com") ? "Big Ambitions-forum"
        : "Kontrolleret kilde";
      return { ...source, label };
    }),
  };
}

export const danishSlugs = Object.keys(copy);
