import type { Locale } from "@/i18n/locales";
import type { Article } from "./types";

const source = {
  capacity: "https://steamcommunity.com/app/1331550/discussions/0/6273017912363121322/",
  equipment: "https://forum.bigambitionsgame.com/t/building-limit-but-why/4159",
  secondary: "https://steamcommunity.com/app/1331550/discussions/0/3826414367726237964/",
  traffic: "https://steamcommunity.com/app/1331550/discussions/0/632295655176427174/",
  jewelry: "https://forum.bigambitionsgame.com/t/is-it-possible-to-max-out-a-jewelry-store-customers-per-hour/3451",
  dailySchedule: "https://steamcommunity.com/app/1331550/discussions/0/600767415367795889/",
  employeeSchedule: "https://steamcommunity.com/app/1331550/discussions/0/6273017912354153121/",
  weeklyHours: "https://steamcommunity.com/app/1331550/discussions/0/591770110121788480/",
  fullTime: "https://steamcommunity.com/app/1331550/discussions/0/4630358783061661172/",
  scheduler: "https://forum.bigambitionsgame.com/t/scheduling-adjustments/4465",
  openingHours: "https://forum.bigambitionsgame.com/t/hi-again/5722",
  priceTest: "https://forum.bigambitionsgame.com/t/law-firm-fee/2900/3",
  onePrice: "https://forum.bigambitionsgame.com/t/a-few-ideas/1872",
  oldPrices: "https://forum.bigambitionsgame.com/t/best-pricing-per-district/4295",
  competitors: "https://forum.bigambitionsgame.com/t/view-competitor-prices-in-market-insider-app/2627",
  importCosts: "https://forum.bigambitionsgame.com/t/paper-bags-for-overseas-wholesale-shipping/3293",
  hq: "https://forum.bigambitionsgame.com/t/link-to-the-head-office-enlace-a-la-oficiona-central/6407",
  desk: "https://steamcommunity.com/app/1331550/discussions/0/591774445091174090/",
  chair: "https://steamcommunity.com/app/1331550/discussions/0/3790380616233523266/",
  deskIdentity: "https://forum.bigambitionsgame.com/t/names-numbered-workstations-to-tell-employees-apart/4038",
  officeTraffic: "https://steamcommunity.com/app/1331550/discussions/0/682988089947205244/",
  officeBlueprint: "https://forum.bigambitionsgame.com/t/office-install-request/7286",
  tutorial: "https://steamcommunity.com/app/1331550/discussions/0/3809535498467803810/",
  balance: "https://forum.bigambitionsgame.com/t/profitability-of-goods/1302",
  store: "https://store.steampowered.com/app/1331550/Big_Ambitions/",
  release: "https://store.steampowered.com/news/app/1331550/view/693137779588071504",
  tutorialUpdate: "https://steamcommunity.com/games/1331550/announcements/detail/497203291915027328",
} as const;

export const growthBusinessArticles: Record<Locale, Article[]> = {
  en: [
    {
      locale: "en", category: "guides", slug: "big-ambitions-customer-capacity",
      keyword: "big ambitions customer capacity",
      title: "Big Ambitions Customer Capacity: Find the Limit",
      description: "Understand Big Ambitions customer capacity, compare equipment with the building limit, and use hourly customer reports to decide what your shop needs next.",
      summary: "Find the equipment category restricting your shop, separate traffic from capacity, and decide when a larger building would help.",
      answer: "Big Ambitions customer capacity is limited by both the building and the equipment supporting each relevant product or service. Improve the lowest capacity category first. A larger register total cannot compensate for an undersized display category, and a higher capacity does not guarantee more customers.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-best-starting-business", "big-ambitions-market-insider", "big-ambitions-product-pricing", "big-ambitions-warehouse-setup"],
      sections: [
        { heading: "Read the building limit and equipment separately", paragraphs: [
          "Open the business in BizMan and inspect its capacity breakdown. Write down the building maximum, then the installed capacity for each relevant equipment or display category. Compare category totals; adding every unrelated item into one grand total hides the actual restriction. The developer's January 2024 explanation identifies the lowest incomplete category as the constraint on the whole business.",
          "Use an invented example to understand the comparison: a building allows 40 customers, one required category supports 30, another supports 50, and checkout supports 60. The structural limit is 30. Raising the 30 category to 45 would leave the building's 40 as the limit. These numbers illustrate the rule; they are not a current furniture catalogue.",
        ] },
        { heading: "Upgrade the category that is actually restricting sales", paragraphs: [
          "Before buying equipment, read its capacity in your game and calculate the total after installation. Check every category shown by the business, including products added after opening. A small secondary range can introduce an equipment requirement that the original layout did not need. The May 2023 developer explanation confirms that an insufficient category can restrict the entire shop.",
          "More stock and more display capacity solve different problems. Filling an existing shelf prevents it from running empty; it does not necessarily change the shelf's capacity rating. Equally, an extra empty display is no substitute for a dependable supply of its product. Inspect both the capacity panel and the inventory before spending money.",
        ], bullets: [
          "1. Record the lowest category and the building maximum.",
          "2. Check the current capacity and price of the matching equipment.",
          "3. Add enough of that category for your intended throughput, then provide its stock and staffing where required.",
          "4. Reopen the capacity breakdown and look for the next lowest category before buying anything else.",
        ] },
        { heading: "Use hourly customers to distinguish a limit from a quiet shop", paragraphs: [
          "In BizMan > Insights, choose Yesterday on the customer graph to examine customers by hour. This view is specifically recommended in developer support. A daily total can conceal a busy lunch period followed by quiet hours: an average below capacity does not prove that no hour was constrained.",
          "Compare several similar trading days with unchanged opening hours. Note the busiest hour, repeated hours near the displayed limit, empty stock, and missing staff. Our practical recommendation is to change one restriction and repeat that comparison. This provides a clearer purchase decision than filling the entire building immediately.",
        ] },
        { heading: "Separate traffic, promotion, and demand", paragraphs: [
          "Traffic Index describes exposure to passing traffic; it is not a second customer ceiling. A developer response from February 2025 explicitly distinguishes the two. Do not interpret a Traffic Index of 30 as an allowance of exactly 30 customers per hour.",
          "When the shop is below its usable capacity, inspect prices, customer feedback, competitors, opening hours, and stock before adding fixtures. The developer also warns that expensive jewelry may never fill a large location. A quiet luxury shop therefore does not automatically have a broken capacity calculation. Increasing capacity creates room for demand; it does not create that demand.",
        ] },
        { heading: "Decide whether to add equipment or change premises", paragraphs: [
          "Additional equipment is the focused purchase when one category sits below the building maximum and observed demand can use more capacity. A different property becomes worth comparing when every relevant category already supports the building maximum and busy hours repeatedly reach it. Include the new fit-out and the cash needed to stock the larger shop in that comparison.",
          "Historical examples contain old equipment prices and ratings. Use their explanation of the constraint, then check the current item and building panels. There is no universal store size or guaranteed customer total that applies to every business type.",
        ] },
        { heading: "Customer capacity questions", paragraphs: [
          "Will another cash register always help? Only if checkout is the restriction and the additional station can operate. It will not lift a lower display category or the building maximum.",
          "Can adding another product reduce capacity? It can introduce a category whose installed capacity is lower. Recheck the breakdown when expanding your range.",
          "Should I advertise a full shop? Extra promotion cannot raise its structural ceiling. Check hourly utilization before paying for more arrivals.",
        ] },
      ],
      sources: [
        { label: "Developer, 13 January 2024: capacity categories and hourly customer graph", href: source.capacity },
        { label: "Developer, 27 May 2023: why displays and buildings both limit capacity", href: source.equipment },
        { label: "Developer, 3 May 2023: added product categories and capacity", href: source.secondary },
        { label: "Developer, 14 February 2025: traffic index is not a customer cap", href: source.traffic },
        { label: "Developer, 9 April 2023: jewelry does not necessarily fill its capacity", href: source.jewelry },
      ],
    },
    {
      locale: "en", category: "guides", slug: "big-ambitions-employee-scheduling",
      keyword: "big ambitions employee scheduling",
      title: "Big Ambitions Employee Scheduling: Fix Your Shifts",
      description: "Plan Big Ambitions employee scheduling around weekly hours, individual days, staff demands, and busy periods, then resolve problems after midweek changes.",
      summary: "Build a schedule that covers the business, respects individual demands, and accounts for hours already worked during the week.",
      answer: "For Big Ambitions employee scheduling, set the business's opening hours first, then assign employees to the required stations on each day. Disable the shared daily schedule when staff need different days off. Check weekly totals and individual demands, including hours already worked before a midweek change.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-office-requirements", "big-ambitions-customer-capacity", "big-ambitions-best-starting-business", "big-ambitions-logistics-manager"],
      sections: [
        { heading: "Set opening hours before assigning people", paragraphs: [
          "Start with the days and hours when the business should serve customers. Then open its schedule and cover the required workstations. The business's opening controls and an employee's assignment are different: closing Tuesday to give one person a day off changes the whole business. A January 2024 developer reply makes this distinction explicitly.",
          "For an established shop, compare the planned hours with its customer graph. Give yourself a reason for extending a quiet morning or late evening: expected extra sales should justify the additional wages. Staff the hours you intend to operate, and review actual demand before expanding that commitment.",
        ] },
        { heading: "Give employees different days without closing the shop", paragraphs: [
          "If editing one day changes the entire week, look for Shared schedule for all days. Turn it off when you need a different weekday and weekend team or an employee has a particular days-off requirement. Click the day itself and edit that day's employee assignments. Developer support confirms this workflow in January 2025.",
          "Use a simple handover plan before dragging names around. For example, one person can cover the weekday opening shift while another covers that station on the weekend, provided each person's actual demands allow it. This is a planning example, not a recommended universal shift length.",
        ], bullets: [
          "1. Read the employee's hours, workday, and time-of-day demands.",
          "2. Disable the shared daily schedule if their days must differ.",
          "3. Select the first day, assign the person to a valid station, and set the intended shift.",
          "4. Review all seven days and cover any gaps with another suitable employee.",
          "5. Recheck each person's weekly total and demand indicators after the edits.",
        ] },
        { heading: "Count weekly hours, including work already completed", paragraphs: [
          "Full-time describes a weekly range, not a promise that any eight-hour shift is valid. A November 2024 developer reply describes full-time as 30–50 hours per week. Read the tooltip in your current save for the employee's actual requirement, and also respect separate requests about days and times.",
          "An eight-hour shift repeated over seven days totals 56 hours. That arithmetic explains why a schedule can look reasonable on a single day and fail over the week. A worker asking for a four-day week also needs the correct number of days; changing only the total hours does not address that request.",
          "Midweek edits are a second trap. In May 2025, the developer explained that employees retain hours worked earlier in the week and that the accounting resets on Monday. A newly displayed acceptable schedule does not erase the shifts already completed. Reduce remaining work where appropriate and assess the corrected pattern across the next full week.",
        ] },
        { heading: "Review autofill instead of assuming its result", paragraphs: [
          "Autofill is useful for creating a draft roster. After using it, inspect uncovered station hours, each employee's demands, and support work such as cleaning. Sort by hours or demands where those controls are available; the developer documented a scheduler overhaul in April 2025. Old complaints about the earlier scheduler do not establish how your installed version behaves.",
          "Our recommended review is a day-by-day pass through the busiest trading window, followed by a person-by-person pass through weekly totals. These catch different mistakes: a satisfied employee does not prove every station has cover, and complete station cover does not prove every employee's requirements are met.",
        ] },
        { heading: "Treat headquarters schedules as a separate case", paragraphs: [
          "Headquarters managers use a fixed schedule. The developer explained in April 2025 that their working week supports management and deliveries across the week. A locked HQ schedule is therefore not evidence that the retail scheduler has stopped working. Check the person's business assignment and desk assignment before trying to extend headquarters opening hours.",
          "After training, a move, or a new hire, inspect the actual scheduled station as part of your routine. Recruiting someone is only the beginning of filling a shift; the roster must still show that person at the intended workplace.",
        ] },
        { heading: "Employee scheduling questions", paragraphs: [
          "Why did a valid-looking schedule leave a demand unmet? Check earlier hours worked, selected weekdays, and separate time restrictions. Weekly totals alone do not cover all demands.",
          "How do I give one employee Friday off? Edit that employee's assignment for Friday, with shared scheduling disabled where needed. Do not close the whole business.",
          "When should I report a bug? If a complete new week still shows a mismatch between the displayed requirements and a valid schedule, include the employee, all seven days, and the game version in a report.",
        ] },
      ],
      sources: [
        { label: "Developer, 12 January 2025: individual days and shared schedules", href: source.dailySchedule },
        { label: "Developer, 11 January 2024: employee assignments versus store opening days", href: source.employeeSchedule },
        { label: "Developer, 24 November 2024: full-time weekly hours", href: source.fullTime },
        { label: "Developer, 1 May 2025: midweek changes and the Monday reset", href: source.weeklyHours },
        { label: "Developer, 1 April 2025: revised scheduler controls", href: source.scheduler },
        { label: "Developer, 15 April 2025: fixed headquarters schedule", href: source.hq },
      ],
    },
    {
      locale: "en", category: "guides", slug: "big-ambitions-product-pricing",
      keyword: "big ambitions product pricing",
      title: "Big Ambitions Product Pricing: Test Better Prices",
      description: "Improve Big Ambitions product pricing with local competitor checks, single-product tests, customer feedback, and margin comparisons using your own sales.",
      summary: "Set useful starting prices, test one product at a time, and judge the result by margin as well as customer feedback.",
      answer: "Tune Big Ambitions product pricing separately for each product and neighborhood. Use local competitor prices as a starting reference, change one product at a time, and allow completed trading days before checking pricing satisfaction and profit. Old maximum-price tables are not reliable promises for a current save.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-purchasing-agent", "big-ambitions-customer-capacity", "big-ambitions-best-investment"],
      sections: [
        { heading: "Choose a local starting price", paragraphs: [
          "Check the product's current selling price and the competitor information available in BizMan. The developer confirmed in March 2024 that the business page can show the lowest competitor price. This is a comparison point, not an instruction to undercut every competitor. Your costs and the response of your customers still decide whether a price is useful.",
          "Record the neighborhood with the price. A developer pricing explanation distinguishes products and districts, so do not copy a successful branch's entire price list into another area without testing it there. Include the current game version in your notes if you intend to reuse the result after an update.",
        ] },
        { heading: "Run a single-product price test", paragraphs: [
          "The developer's March 2023 procedure is to raise a price gradually, wait a day or two, and inspect pricing satisfaction in BizMan > Insights. A separate developer reply recommends changing one item at a time because store-level feedback otherwise makes the offending product hard to identify. This is a practical experiment, not proof that a satisfaction threshold always maximizes profit.",
          "Choose a product with stable availability. Keep opening hours, staffing, advertising, and the rest of the price list as steady as possible. If stock runs out during the test, mark that day as disrupted: the missing sales cannot tell you cleanly whether shoppers rejected the new price.",
        ], bullets: [
          "1. Note the original price, unit purchase cost, units sold, and pricing feedback.",
          "2. Change only the chosen product by a modest amount you can compare easily.",
          "3. Let completed trading days pass before inspecting the result.",
          "4. Compare units sold and gross contribution alongside pricing satisfaction.",
          "5. Keep or reverse the change, record the result, and only then test another product.",
        ] },
        { heading: "Compare money earned after product costs", paragraphs: [
          "A higher selling price can earn less if too many sales disappear. For retail stock, compare units sold × (selling price − unit purchase cost). This is ordinary bookkeeping for your experiment, not a hidden formula for the game's complete profit calculation. Rent, wages, marketing, and other expenses still need to be deducted to assess the business.",
          "Consider an invented example: selling 100 units at a price of 12 with a cost of 7 gives 500 before other expenses. Selling 75 units at 14 gives 525. The higher price improves that product's contribution in this example despite fewer sales. Use your own numbers; the example is not a recommendation for any particular item.",
          "Office services need a different cost check because payroll matters more than a purchased retail unit. Compare service revenue with the staff needed to deliver it. A fee that attracts extra clients can disappoint if serving them requires more wages than the additional income covers.",
        ] },
        { heading: "Keep supplier costs and customer prices separate", paragraphs: [
          "When a product's margin changes, inspect the amount you pay as well as the amount you charge. The developer's April 2023 importing explanation connects contract pricing with the import index and Purchasing Agent skill when the contract is created. A copied sales price therefore does not imply that two businesses have identical margins.",
          "Our practical recommendation is to note the supplier cost on every pricing comparison. If a new contract changes that cost during the test, split the results into before and after. Otherwise a purchasing improvement can look like a successful retail price increase, or a cost rise can disguise one.",
        ] },
        { heading: "Use the Pricing Manager after establishing your baseline", paragraphs: [
          "The official 1.0 changelog introduces a headquarters Pricing Manager who can change item prices across an entire neighborhood. Higher-skilled managers also offer daily price suggestions. Check which businesses a change will affect, then compare the results with your recorded baseline before accepting another broad adjustment.",
          "In June 2023, the developer explicitly described the earlier cheat sheet as out of date and invited community price suggestions. That history is a reason to date reference tables and retest them, not a reason to publish their old amounts as current maximums. Product mix, neighborhood, employee state, and later balance changes all deserve checking.",
          "Repeat a targeted test when pricing feedback changes materially, a supplier contract changes, or a branch moves. Avoid resetting every price at once simply because one product performs badly. Preserving a known baseline makes the next decision easier to explain.",
        ] },
        { heading: "Product pricing questions", paragraphs: [
          "Should pricing satisfaction always be perfect? It is useful feedback, but it does not by itself show the highest profit. Compare the income and costs of the alternatives.",
          "Should I copy the lowest competitor? Use it to understand the local market, then test. Matching a rival is not evidence that your costs are covered.",
          "Why did sales fall after a price change? Check stock, staff cover, trading hours, and local competition before attributing the entire decline to price.",
        ] },
      ],
      sources: [
        { label: "Official 1.0 changelog, published 14 August 2026: Pricing Manager", href: source.release },
        { label: "Developer, 31 March 2024: competitor prices in BizMan", href: source.competitors },
        { label: "Developer, 22 March 2023: incremental prices and feedback delay", href: source.priceTest },
        { label: "Developer, 15 October 2022: isolate one product's price", href: source.onePrice },
        { label: "Developer, 9–10 April 2023: supplier contracts and purchasing costs", href: source.importCosts },
        { label: "Developer, 4 June 2023: older price tables are out of date", href: source.oldPrices },
      ],
    },
    {
      locale: "en", category: "guides", slug: "big-ambitions-office-requirements",
      keyword: "big ambitions office requirements",
      title: "Big Ambitions Office Requirements: Desks and Staff",
      description: "Check Big Ambitions office requirements for workstations, employee demands, desk assignments, and headquarters, then test the setup before adding more staff.",
      summary: "Understand what makes an office workstation usable and why a revenue office follows different rules from headquarters.",
      answer: "Big Ambitions office requirements include usable desk, computer and chair combinations, the required toilets and sinks, suitable employees, and scheduled workstation assignments. Check business requirements and individual demands before opening. Headquarters has no customer-capacity restriction of the retail kind, while a service office still depends on its market.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-employee-scheduling", "big-ambitions-purchasing-agent", "big-ambitions-logistics-manager", "big-ambitions-where-to-buy-bathroom-stall"],
      sections: [
        { heading: "Decide whether the office serves clients or manages businesses", paragraphs: [
          "A law firm or another office service business earns revenue from clients. Headquarters houses management roles such as Purchasing Agents, Logistics Managers, and HR Managers. The official store description confirms that those managers require office infrastructure. Decide which function you are creating before hiring or copying a layout, because a furnished room is not itself an operating business.",
          "For a service business, inspect local demand and compare property details with the planned team. Do not assume online client handling makes location irrelevant: a December 2025 developer reply explicitly confirms that Traffic Index still affects office businesses. For headquarters, evaluate how many usable workstations and demanded amenities fit without paying for unnecessary space.",
        ] },
        { heading: "Build and validate one complete workstation", paragraphs: [
          "Begin with one desk, its computer, and a correctly attached chair. Check the game's placement feedback and any warning on the computer before duplicating the arrangement. Historical developer support identifies chair position and desk orientation as causes of a computer reporting a missing chair. Furniture that appears close together can still fail to form a usable station.",
          "Include toilets and sinks in the opening plan. The official EA 0.9 notes make office bathrooms a requirement based on building size and warn that an office missing them will not earn money. Use the current requirements panel for the exact fixtures and quantities; a desk-only blueprint is incomplete.",
          "Once the station is recognized, keep access and room for employee-specific additions. Our recommendation is to validate one small group before furnishing the whole premises. If the prototype cannot accept an employee, multiplying it creates a larger repair job instead of more working capacity.",
        ], bullets: [
          "1. Read the current business and employee requirements before ordering furniture.",
          "2. Place the desk and computer, then attach the chair in the valid orientation.",
          "3. Resolve workstation warnings, install the required bathroom fixtures, and preserve access.",
          "4. Assign one suitable employee and confirm that the station appears in the schedule.",
          "5. Expand the tested arrangement only after the first worker is correctly assigned.",
        ] },
        { heading: "Assign people to desks, not just to the company", paragraphs: [
          "Hiring a manager does not automatically place them at a working computer. Assign the employee to the intended business and then inspect that business's schedule. A June 2025 developer support case about Purchasing Agents was resolved by assigning them to available desk slots that the player had mistaken for weekend shifts.",
          "Read the selected day and scroll through the entire workstation list before concluding that the office has no space. An empty workstation near the bottom is not necessarily a different day's shift. After assignment, open the relevant management screen and confirm that the person is available for the intended role.",
        ] },
        { heading: "Match individual demands to the correct station", paragraphs: [
          "Compare the employee's requested furniture with the items attached to the desk they actually use. Buying the right chair elsewhere in the same office does not establish that this person's station has it. The developer has recommended inspecting the workstation information in the scheduler to identify the attached equipment; use the current interface's identification tools before replacing a row of desks.",
          "Different employees can need different additions, so avoid treating an attractive blueprint as proof that every demand is satisfied. In February 2026, the developer pointed out that the main-menu blueprint creator can edit existing layouts. Use that option for a repeatable office specification, then still check the installed result against your actual staff.",
        ] },
        { heading: "Check headquarters limits and service-office performance", paragraphs: [
          "In April 2025, the developer clarified that headquarters has no customers and can hold employees according to how many desks fit. Its locked work schedule supports management across the week. Do not transfer a customer limit from a service office into an assumed hard manager limit, or try to create an evening headquarters shift to unlock an unused desk.",
          "For a service office, our recommendation is to compare clients served with the team you pay before adding more desks. A valid station creates the ability to work, not a guaranteed client. Keep hiring, equipment spending, and price changes separate enough that you can tell which change improves the business.",
        ] },
        { heading: "Office requirements questions", paragraphs: [
          "The computer says a chair is missing. What should I check? Inspect the chair's attachment and the desk's direction. Revalidate one station before rebuilding the office.",
          "Do all offices ignore Traffic Index? No. Developer support confirms that it still matters for service offices. Headquarters is a different management function.",
          "Does a blueprint finish the setup? It can provide the furniture layout. You still need to inspect placement, employee demands, and assignments for your own team.",
          "Is there one furniture shopping list for every office? No. Use the current business requirements and each employee's demands; this guide deliberately avoids a universal item count or fixed opening budget.",
        ] },
      ],
      sources: [
        { label: "Official store: headquarters and management roles", href: source.store },
        { label: "Official EA 0.9 preview, 12 August 2025: office bathroom requirements", href: source.tutorialUpdate },
        { label: "Developer, 9 May 2023: chair attachment and desk orientation", href: source.chair },
        { label: "Developer, 17–18 June 2025: scheduling managers at desks", href: source.desk },
        { label: "Developer, June 2023: identify the furniture attached to a workstation", href: source.deskIdentity },
        { label: "Developer, 15 April 2025: headquarters capacity and schedule", href: source.hq },
        { label: "Developer, 8 December 2025: office traffic still matters", href: source.officeTraffic },
        { label: "Developer, 17 February 2026: edit an office blueprint", href: source.officeBlueprint },
      ],
    },
    {
      locale: "en", category: "guides", slug: "big-ambitions-best-starting-business",
      keyword: "big ambitions best starting business",
      title: "Big Ambitions Best Starting Business: Pick Your First",
      description: "Choose the Big Ambitions best starting business for your save by comparing a small gift shop, local demand, equipment costs, staffing, and your cash reserves.",
      summary: "Consider a small gift shop or compare affordable alternatives using an opening budget, current tutorial objectives, and a first-week plan.",
      answer: "For a first playthrough, our recommendation is a small gift shop if local demand and your budget support it. This teaches stocking, checkout, prices, and shifts; it is an optional choice, not a fixed tutorial requirement. The best business is one you can fully equip and keep supplied without using all your cash.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-customer-capacity", "big-ambitions-employee-scheduling", "big-ambitions-warehouse-setup", "big-ambitions-best-investment"],
      sections: [
        { heading: "Use the gift shop to learn a complete operating loop", paragraphs: [
          "The first business should teach you how a store opens, gets stock, serves customers, and pays its expenses. A gift shop provides a concrete retail route through those tasks. This is our beginner recommendation based on learning the system, not a claim that gifts provide the game's highest margins.",
          "If you are following Uncle Fred's objectives, read the current task before renting or recruiting. The tutorial has changed: the official 1.0 changelog describes hiring objectives that adapt to businesses such as gyms and hairdressers. A gift shop is therefore our suggested learning option, not a business that every current tutorial forces you to open. Older walkthroughs can describe narrower requirements.",
        ] },
        { heading: "Compare three possible starts by what you must manage", paragraphs: [
          "For a free-choice start, shortlist a gift shop, a food or coffee concept, and an office service you are interested in. The official game description confirms these broad business options, but it does not rank them. Price a complete opening setup for each using the live requirements rather than judging by a single expensive item.",
          "A gift shop lets you focus on displays, stock, and checkout. A food or coffee concept adds the need to understand each required appliance category and its capacity. An office shifts your attention toward usable workstations, specialist employees, and whether enough clients arrive to justify payroll. Choose the operating loop you can currently fund and manage.",
          "Do not promote a late-game profit screenshot into a beginner recommendation. A store with a large trained workforce, negotiated supply contracts, and a mature market position is a different investment from an opening-day business bought with limited cash.",
        ] },
        { heading: "Check the neighborhood before committing to the concept", paragraphs: [
          "Inspect the relevant products or services in Market Insider for the candidate neighborhood, then examine the available properties. Note local competition, displayed demand, rent, and building capacity. Capacity determines possible throughput, while the market determines whether enough customers may use it. A large room alone does not settle that question.",
          "The developer's customer-capacity explanation also identifies competition as a factor in demand. Our recommendation is to compare at least two candidate locations before committing your setup money. Write down what makes the chosen combination workable: affordable rent, a product opportunity, or a smaller equipment plan that preserves cash for staffing.",
        ] },
        { heading: "Prepare an opening budget and a replenishment budget", paragraphs: [
          "Separate the money needed to open from the money needed to stay open. Your opening list includes lease-related charges shown in the game, required equipment, initial stock, and installation or delivery costs you choose to incur. Your operating list includes restocking, wages, rent, and other recurring commitments displayed for the business.",
          "Our practical rule is to reject a plan that leaves no money for the next stock order or payroll. There is no universal cash reserve in this guide: calculate it from your own expected expenses. Optional decoration, a broader product range, and a larger property can wait until you know the first setup works.",
        ], bullets: [
          "1. Price the minimum complete setup for the chosen business in the current game.",
          "2. Add initial inventory and the next expected replenishment order.",
          "3. Add scheduled wages and other recurring costs for your planned review period.",
          "4. Keep additional cash for a missed delivery, replacement equipment, or a staffing correction.",
          "5. Open only when both the setup and the operating plan fit the money available.",
        ] },
        { heading: "Make the first location repeatable before expanding", paragraphs: [
          "After opening, review hourly customers, empty stock, employee requirements, and the store's income and expenses. Solve one problem at a time. If a product sells out, fix replenishment; if checkout lacks cover, repair the schedule; if the business stays quiet, revisit its hours, prices, and market before renting more space.",
          "Before opening a second location, aim for a first store that completes its planned trading days without constant emergency shopping or you covering every shift. This is an editorial milestone for manageable expansion. It does not require buying headquarters immediately; add infrastructure when it solves a measured workload.",
        ] },
        { heading: "Starting business questions", paragraphs: [
          "Is a gift shop always the most profitable start? No. It is an optional learning route. Profit depends on the actual location and operating costs.",
          "Should I start with the business an old guide calls overpowered? Recheck it. The developer explicitly noted substantial business-balance changes in June 2023; old rankings should be dated examples.",
          "What if the tutorial does not accept my shop? Compare its business type and property details with the current objective before buying more inventory or equipment.",
        ] },
      ],
      sources: [
        { label: "Official store: business choices, staffing, and infrastructure", href: source.store },
        { label: "Official 1.0 changelog, published 14 August 2026: adaptive hiring objectives", href: source.release },
        { label: "Developer, 27 May 2023: equipment requirements and capacity", href: source.equipment },
        { label: "Developer, 13 January 2024: competition, demand, and customer limits", href: source.capacity },
        { label: "Developer, 13 June 2023: business profitability changed with balancing", href: source.balance },
      ],
    },
  ],
  de: [
    {
      locale: "de", category: "guides", slug: "big-ambitions-customer-capacity",
      keyword: "Big Ambitions Kundenkapazität",
      title: "Big Ambitions Kundenkapazität: Engpässe erkennen",
      description: "Prüfe die Big Ambitions Kundenkapazität anhand von Gebäude, Ausstattung und stündlichen Kundenzahlen, bevor du Geräte kaufst oder den Standort wechselst.",
      summary: "Erkenne die begrenzende Ausstattung, unterscheide Laufkundschaft von Kapazität und plane einen Ausbau anhand tatsächlicher Kundenzahlen.",
      answer: "Die Big Ambitions Kundenkapazität hängt vom Gebäude und den relevanten Ausstattungskategorien ab. Die niedrigste Kapazität begrenzt den Betrieb. Zusätzliche Kassen gleichen zu wenige Verkaufsregale nicht aus; eine höhere Kapazität bringt außerdem nicht automatisch mehr Kunden.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-best-starting-business", "big-ambitions-market-insider", "big-ambitions-product-pricing", "big-ambitions-warehouse-setup"],
      sections: [
        { heading: "Gebäude und Ausstattung getrennt vergleichen", paragraphs: [
          "Öffne die Kapazitätsübersicht des Geschäfts in BizMan. Vergleiche die Gebäudegrenze mit der Summe innerhalb jeder benötigten Ausstattungskategorie. Addiere Kassen, Regale und andere Kategorien nicht zu einer gemeinsamen Kapazität.",
          "Rechenbeispiel mit erfundenen Werten: Das Gebäude erlaubt 40 Kunden, eine benötigte Kategorie schafft 30, eine andere 50. Dann begrenzt die Kategorie mit 30 den Betrieb. Steigerst du sie auf 45, bleibt die Gebäudegrenze von 40. Aktuelle Gerätewerte liest du im Spiel ab.",
        ] },
        { heading: "Die begrenzende Kategorie gezielt erweitern", paragraphs: [
          "Auch ein später hinzugefügtes Produkt kann eine zusätzliche Ausstattungskategorie erfordern. Prüfe deshalb nach einer Sortimentserweiterung die gesamte Übersicht. Ein voller Warenbestand erhöht nicht automatisch die Kapazitätsbewertung des Regals.",
        ], bullets: [
          "1. Niedrigste Kategorie und Gebäudegrenze notieren.",
          "2. Kapazität und Preis des passenden Geräts im aktuellen Spiel prüfen.",
          "3. Die benötigte Ausstattung ergänzen und Waren sowie Personal bereitstellen.",
          "4. Die Übersicht erneut öffnen und den nächsten Engpass suchen.",
        ] },
        { heading: "Spitzenstunden statt Tagesdurchschnitt prüfen", paragraphs: [
          "Stelle die Kundengrafik unter BizMan > Insights auf den Vortag. Der Entwickler empfiehlt diese Ansicht für die stündliche Auswertung. Ein niedriger Tagesdurchschnitt kann ausgelastete Mittagsstunden verdecken.",
          "Vergleiche mehrere ähnliche Verkaufstage. Notiere Spitzenstunden, leere Bestände und unbesetzte Stationen. Unsere Empfehlung: zuerst einen Engpass beheben und anschließend dieselben Stunden erneut prüfen.",
        ] },
        { heading: "Laufkundschaft und Nachfrage richtig einordnen", paragraphs: [
          "Der Traffic Index beschreibt den möglichen Kundenstrom und ist keine zweite feste Kundengrenze. Ein Wert von 30 bedeutet also nicht genau 30 Kunden pro Stunde. Die Entwicklerbestätigung hierzu stammt vom Februar 2025.",
          "Bleibt die Auslastung niedrig, prüfe Preise, Konkurrenz, Öffnungszeiten und Verfügbarkeit. Teure Waren wie Schmuck können trotz großer Räume weniger Kunden anziehen. Vergleiche größere Immobilien erst dann, wenn die Ausstattung die Gebäudegrenze erreicht und starke Stunden wiederholt daran stoßen.",
        ] },
        { heading: "Fragen zur Kundenkapazität", paragraphs: [
          "Hilft eine zusätzliche Kasse immer? Nur wenn die Kassenkapazität tatsächlich begrenzt und die Station betrieben werden kann.",
          "Kann ein neues Produkt die Kapazität senken? Ja, wenn seine erforderliche Ausstattung zur niedrigsten Kategorie wird.",
          "Lohnt mehr Werbung bei voller Auslastung? Werbung erhöht die Gebäudegrenze nicht. Prüfe zunächst, ob freie Kapazität vorhanden ist.",
        ] },
      ],
      sources: [
        { label: "Entwickler, 13. Januar 2024: Kapazität und stündliche Kundengrafik", href: source.capacity },
        { label: "Entwickler, 27. Mai 2023: Grenzen von Gebäude und Ausstattung", href: source.equipment },
        { label: "Entwickler, 3. Mai 2023: zusätzliche Produktkategorien", href: source.secondary },
        { label: "Entwickler, 14. Februar 2025: Traffic Index und Kapazität", href: source.traffic },
        { label: "Entwickler, 9. April 2023: Kundenzahlen bei Schmuck", href: source.jewelry },
      ],
    },
    {
      locale: "de", category: "guides", slug: "big-ambitions-employee-scheduling",
      keyword: "Big Ambitions Personalplanung",
      title: "Big Ambitions Personalplanung: Schichten richtig setzen",
      description: "Nutze die Big Ambitions Personalplanung für passende Wochentage, Arbeitsstunden und Mitarbeiterwünsche und prüfe nach Änderungen bereits geleistete Stunden.",
      summary: "Plane einzelne Tage, kontrolliere Wochenstunden und erkenne, warum Änderungen mitten in der Woche nicht alle Warnungen beseitigen.",
      answer: "Lege zuerst die Öffnungszeiten des Geschäfts fest und besetze anschließend die Stationen. Deaktiviere den gemeinsamen Tagesplan, wenn Mitarbeiter unterschiedliche freie Tage brauchen. Prüfe Wochenstunden, persönliche Wünsche und bereits geleistete Arbeit vor einer Änderung mitten in der Woche.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-office-requirements", "big-ambitions-customer-capacity", "big-ambitions-best-starting-business", "big-ambitions-logistics-manager"],
      sections: [
        { heading: "Öffnungszeiten und Mitarbeiterschichten unterscheiden", paragraphs: [
          "Ein geschlossener Geschäftstag betrifft das gesamte Unternehmen. Möchtest du nur einer Person freigeben, ändere deren Zuweisung im Dienstplan. Die Öffnungszeiten sind dafür der falsche Schalter.",
          "Vergleiche bei einem laufenden Geschäft die geplanten Stunden mit der Kundengrafik. Zusätzliche Früh- oder Spätschichten sollten genug Verkäufe ermöglichen, um ihren Lohnaufwand zu rechtfertigen.",
        ] },
        { heading: "Unterschiedliche Wochentage einrichten", paragraphs: [
          "Deaktiviere die gemeinsame Planung für alle Tage, wenn Werktage und Wochenende anders besetzt werden sollen. Wähle danach den einzelnen Wochentag aus. Dieser Ablauf wurde im Januar 2025 vom Entwickler bestätigt.",
        ], bullets: [
          "1. Stunden-, Tages- und Uhrzeitwünsche jeder Person lesen.",
          "2. Bei unterschiedlichen Tagen die gemeinsame Tagesplanung ausschalten.",
          "3. Jeden Tag auswählen und die passende Station besetzen.",
          "4. Lücken durch geeignetes Personal schließen und Wochenstunden kontrollieren.",
        ] },
        { heading: "Wochenstunden nach Änderungen kontrollieren", paragraphs: [
          "Vollzeit bezieht sich auf die Woche. Der Entwickler nannte im November 2024 einen Bereich von 30–50 Stunden; maßgeblich bleibt die aktuelle Anforderung im Spiel. Acht Stunden an sieben Tagen ergeben bereits 56 Stunden.",
          "Bei Änderungen mitten in der Woche zählt bereits geleistete Arbeit weiter. Laut Entwicklerantwort vom Mai 2025 wird diese Wochenrechnung montags zurückgesetzt. Ein neuer Plan löscht die bisherigen Schichten nicht. Prüfe außerdem separate Wünsche wie eine Vier-Tage-Woche.",
        ] },
        { heading: "Automatische Planung und Hauptsitz prüfen", paragraphs: [
          "Kontrolliere nach dem automatischen Ausfüllen sowohl offene Stationsstunden als auch die Wünsche jeder Person. Die Planungsoberfläche wurde laut Entwickler im April 2025 überarbeitet; alte Fehlerberichte beschreiben deshalb nicht unbedingt deine aktuelle Version.",
          "Der Hauptsitz hat einen festen Arbeitsplan für Verwaltungsaufgaben. Ist dessen Zeitplan gesperrt, prüfe die Zuweisung zu Unternehmen und Schreibtisch. Eine zusätzliche Abendschicht ist nicht der vorgesehene Weg, einen freien Platz nutzbar zu machen.",
        ] },
        { heading: "Fragen zur Personalplanung", paragraphs: [
          "Warum bleibt eine Stundenwarnung bestehen? Prüfe frühere Arbeit in dieser Woche sowie separate Tages- und Zeitwünsche.",
          "Wie erhält nur eine Person Freitag frei? Entferne ihre Freitagszuweisung und besetze die Station anderweitig, ohne den Betrieb zu schließen.",
          "Wann ist ein Fehlerbericht sinnvoll? Wenn eine vollständige neue Woche trotz erfüllter Anforderungen weiterhin eine Abweichung zeigt. Dokumentiere alle sieben Tage und die Spielversion.",
        ] },
      ],
      sources: [
        { label: "Entwickler, 12. Januar 2025: einzelne Wochentage planen", href: source.dailySchedule },
        { label: "Entwickler, 11. Januar 2024: Öffnungstage und einzelne Mitarbeiter", href: source.employeeSchedule },
        { label: "Entwickler, 24. November 2024: Vollzeitstunden", href: source.fullTime },
        { label: "Entwickler, 1. Mai 2025: bereits geleistete Wochenstunden", href: source.weeklyHours },
        { label: "Entwickler, 1. April 2025: überarbeitete Planung", href: source.scheduler },
        { label: "Entwickler, 15. April 2025: fester Hauptsitzplan", href: source.hq },
      ],
    },
    {
      locale: "de", category: "guides", slug: "big-ambitions-product-pricing",
      keyword: "Big Ambitions Produktpreise",
      title: "Big Ambitions Produktpreise: Preise gezielt testen",
      description: "Passe die Big Ambitions Produktpreise mit lokalen Konkurrenzwerten, einzelnen Preistests und einer Kontrolle von Absatz, Einkaufskosten und Gewinn gezielt an.",
      summary: "Teste jeweils ein Produkt und vergleiche den Ertrag nach Einkaufskosten, statt nur auf den höchsten Verkaufspreis zu achten.",
      answer: "Teste die Big Ambitions Produktpreise je Produkt und Stadtviertel. Nutze Konkurrenzpreise als Ausgangspunkt, ändere jeweils einen Preis und prüfe nach abgeschlossenen Verkaufstagen die Preiszufriedenheit sowie den Ertrag. Alte Höchstpreislisten sind keine verlässliche Zusage für deinen Spielstand.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-purchasing-agent", "big-ambitions-customer-capacity", "big-ambitions-best-investment"],
      sections: [
        { heading: "Mit einem lokalen Vergleich beginnen", paragraphs: [
          "Prüfe den aktuellen Produktpreis und die Konkurrenzangaben in BizMan. Der Entwickler bestätigte im März 2024 die Anzeige des niedrigsten Konkurrenzpreises. Diesen Wert musst du nicht automatisch unterbieten: Entscheidend sind deine Kosten und die Kundenreaktion.",
          "Notiere das Stadtviertel. Ein Preis, der in einer Filiale funktioniert, sollte bei einem Standort in einem anderen Viertel erneut getestet werden.",
        ] },
        { heading: "Jeweils nur ein Produkt verändern", paragraphs: [
          "Der Entwickler empfiehlt, Preise schrittweise zu erhöhen und nach ein bis zwei Tagen die Preiszufriedenheit in BizMan > Insights zu prüfen. Ändere nicht das ganze Sortiment gleichzeitig, sonst lässt sich eine Verschlechterung schwer einem Produkt zuordnen.",
        ], bullets: [
          "1. Ausgangspreis, Einkaufskosten, verkaufte Menge und Rückmeldung notieren.",
          "2. Nur den ausgewählten Produktpreis geringfügig verändern.",
          "3. Öffnungszeiten, Personal und Werbung möglichst konstant halten.",
          "4. Nach abgeschlossenen Verkaufstagen Absatz und Ertrag vergleichen.",
          "5. Änderung behalten oder zurücknehmen, bevor der nächste Test beginnt.",
        ] },
        { heading: "Den Ertrag nach Einkaufskosten vergleichen", paragraphs: [
          "Für Handelsware hilft diese Rechnung: verkaufte Menge × (Verkaufspreis − Einkaufspreis je Einheit). Sie zeigt den Produktbeitrag vor Miete, Löhnen und anderen Ausgaben, nicht den vollständigen Geschäftsgewinn.",
          "Erfundenes Beispiel: 100 Stück zu 12 bei Einkaufskosten von 7 ergeben 500 vor weiteren Kosten. 75 Stück zu 14 ergeben 525. Weniger Verkäufe können also trotzdem mehr beitragen. Bei Bürodienstleistungen musst du besonders den zusätzlichen Personalaufwand berücksichtigen.",
        ] },
        { heading: "Preismanager, Beschaffungskosten und Referenzen prüfen", paragraphs: [
          "Der offizielle Änderungsbericht zu 1.0 führt einen Preismanager im Hauptsitz ein, der Produktpreise für ein ganzes Viertel ändern kann. Erfahrenere Mitarbeiter geben tägliche Preisvorschläge. Prüfe den betroffenen Bereich und vergleiche das Ergebnis mit deinen bisherigen Werten.",
          "Notiere die Lieferkosten beim Test. Der Entwickler erklärt, dass Importindex und die Fähigkeit des Einkaufsmitarbeiters bei Vertragserstellung den Einkaufspreis beeinflussen. Ein neuer Liefervertrag kann den Ertrag ändern, ohne dass dein Verkaufspreis die Ursache ist.",
          "Bereits im Juni 2023 bezeichnete der Entwickler frühere Preislisten als veraltet. Nutze solche Tabellen höchstens als datierte Ausgangspunkte. Wiederhole einen gezielten Test nach deutlichen Veränderungen bei Kosten, Standort oder Kundenfeedback.",
        ] },
        { heading: "Fragen zu Produktpreisen", paragraphs: [
          "Ist perfekte Preiszufriedenheit immer optimal? Sie ist eine hilfreiche Rückmeldung, ersetzt aber keinen Vergleich von Einnahmen und Kosten.",
          "Warum sinkt der Absatz? Prüfe auch leere Bestände, fehlendes Personal und geänderte Öffnungszeiten. Nicht jeder Rückgang entsteht durch den Preis.",
          "Soll ich alle Filialen gleich bepreisen? Prüfe die örtlichen Bedingungen und teste pro Viertel, statt eine universelle Liste anzunehmen.",
        ] },
      ],
      sources: [
        { label: "Offizieller Änderungsbericht zu 1.0 vom 14. August 2026: Preismanager", href: source.release },
        { label: "Entwickler, 31. März 2024: Konkurrenzpreise in BizMan", href: source.competitors },
        { label: "Entwickler, 22. März 2023: schrittweise Preistests", href: source.priceTest },
        { label: "Entwickler, 15. Oktober 2022: ein Produkt nach dem anderen", href: source.onePrice },
        { label: "Entwickler, 9.–10. April 2023: Importkosten", href: source.importCosts },
        { label: "Entwickler, 4. Juni 2023: veraltete Preislisten", href: source.oldPrices },
      ],
    },
    {
      locale: "de", category: "guides", slug: "big-ambitions-office-requirements",
      keyword: "Big Ambitions Büroanforderungen",
      title: "Big Ambitions Büroanforderungen: Plätze und Personal",
      description: "Prüfe die Big Ambitions Büroanforderungen für Schreibtische, Computer, Stühle und Mitarbeiter und unterscheide Dienstleistungsbüros vom eigenen Hauptsitz.",
      summary: "Richte gültige Arbeitsplätze ein, ordne Mitarbeiter zu und prüfe ihre Wünsche, bevor du weitere Schreibtische kaufst.",
      answer: "Ein Büro braucht gültige Schreibtisch-, Computer- und Stuhlkombinationen, die vorgeschriebenen Toiletten und Waschbecken sowie passende Mitarbeiter mit Stationszuweisung. Prüfe betriebliche Anforderungen und persönliche Wünsche. Ein Hauptsitz verwaltet Unternehmen; ein Dienstleistungsbüro benötigt einen tragfähigen Kundenmarkt.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-employee-scheduling", "big-ambitions-purchasing-agent", "big-ambitions-logistics-manager", "big-ambitions-where-to-buy-bathroom-stall"],
      sections: [
        { heading: "Hauptsitz und Dienstleistungsbüro unterscheiden", paragraphs: [
          "Eine Kanzlei verdient an Kunden. Im Hauptsitz arbeiten Verwaltungsrollen wie Einkaufs-, Logistik- und Personalmanager. Entscheide den Zweck vor der Einrichtung und Einstellung.",
          "Der Traffic Index bleibt bei Dienstleistungsbüros relevant; das bestätigte der Entwickler im Dezember 2025. Beim Hauptsitz steht dagegen im Vordergrund, wie viele gültige Arbeitsplätze und benötigte Einrichtungen in den Raum passen.",
        ] },
        { heading: "Einen vollständigen Arbeitsplatz testen", paragraphs: [
          "Beginne mit einem Schreibtisch, Computer und korrekt zugeordneten Stuhl. Bei einer Stuhlwarnung prüfst du Position und Ausrichtung: Der Entwickler nennt eine falsche Schreibtischrichtung als mögliche Ursache.",
          "Plane Toiletten und Waschbecken ein. Seit EA 0.9 benötigen Büros Sanitäranlagen entsprechend der Gebäudegröße; fehlen sie, verdient das Büro laut offiziellen Hinweisen kein Geld. Die aktuelle Anforderungsanzeige bestimmt Art und Anzahl der Einrichtungen.",
        ], bullets: [
          "1. Aktuelle Anforderungen des Geschäfts und Mitarbeiters lesen.",
          "2. Schreibtisch, Computer und Stuhl gültig platzieren.",
          "3. Warnungen beseitigen, Sanitäranlagen ergänzen und Zugang freihalten.",
          "4. Eine passende Person im Dienstplan zuweisen.",
          "5. Erst den funktionierenden Aufbau vervielfachen.",
        ] },
        { heading: "Mitarbeiter der richtigen Station zuordnen", paragraphs: [
          "Eine Einstellung allein besetzt noch keinen Computer. Prüfe die Zuweisung zum Unternehmen und anschließend zum Arbeitsplatz. Scrolle durch die vollständige Stationsliste und kontrolliere den ausgewählten Tag.",
          "Ein Entwicklerfall vom Juni 2025 zeigt einen typischen Irrtum: Freie Plätze am Listenende wurden für Wochenendschichten gehalten. Nach korrekter Zuweisung funktionierten die Einkaufsmitarbeiter.",
        ] },
        { heading: "Wünsche, Vorlagen und Grenzen kontrollieren", paragraphs: [
          "Vergleiche gewünschte Möbel mit der tatsächlichen Ausstattung der zugewiesenen Station. Der passende Stuhl an einem anderen Schreibtisch belegt nicht, dass dieser Mitarbeiter seinen Wunsch erfüllt bekommt. Nutze die Arbeitsplatzinformationen zur Zuordnung.",
          "Bestehende Baupläne lassen sich laut Entwickler im Bauplaneditor des Hauptmenüs bearbeiten. Prüfe trotzdem die installierte Ausstattung und die Anforderungen deines Teams.",
          "Der Hauptsitz hat laut Entwickler keine Kundengrenze wie ein Verkaufsgeschäft; entscheidend sind passende Schreibtischplätze. Sein Arbeitsplan ist fest. In einem Dienstleistungsbüro sollten zusätzliche Stellen dagegen durch genügend Kundengeschäft gerechtfertigt sein.",
        ] },
        { heading: "Fragen zur Büroeinrichtung", paragraphs: [
          "Warum fehlt angeblich ein Stuhl? Prüfe die Verbindung zur Station und die Ausrichtung des Schreibtischs.",
          "Erledigt ein Bauplan alles? Er hilft bei der Einrichtung. Personalzuweisung und individuelle Wünsche musst du weiterhin kontrollieren.",
          "Gibt es eine universelle Einkaufsliste? Nein. Geschäftstyp, aktuelle Anforderungen und Mitarbeiterwünsche entscheiden über die benötigten Gegenstände.",
        ] },
      ],
      sources: [
        { label: "Offizielle Shopseite: Verwaltungsrollen und Hauptsitz", href: source.store },
        { label: "Offizielle Vorschau zu EA 0.9 vom 12. August 2025: Sanitäranlagen in Büros", href: source.tutorialUpdate },
        { label: "Entwickler, 9. Mai 2023: Stuhl und Schreibtischrichtung", href: source.chair },
        { label: "Entwickler, 17.–18. Juni 2025: Arbeitsplatzzuweisung", href: source.desk },
        { label: "Entwickler, Juni 2023: Arbeitsplatzausstattung erkennen", href: source.deskIdentity },
        { label: "Entwickler, 15. April 2025: Hauptsitz und Kapazität", href: source.hq },
        { label: "Entwickler, 8. Dezember 2025: Traffic Index bei Büros", href: source.officeTraffic },
        { label: "Entwickler, 17. Februar 2026: Bürobaupläne bearbeiten", href: source.officeBlueprint },
      ],
    },
    {
      locale: "de", category: "guides", slug: "big-ambitions-best-starting-business",
      keyword: "Big Ambitions bestes Startgeschäft",
      title: "Big Ambitions bestes Startgeschäft: sinnvoll wählen",
      description: "Wähle dein Big Ambitions bestes Startgeschäft mit einem Vergleich von Tutorial, örtlicher Nachfrage, Einrichtung, Personal und Geld für den laufenden Betrieb.",
      summary: "Erwäge einen kleinen Geschenkeshop oder vergleiche bezahlbare Alternativen anhand eines vollständigen Eröffnungs- und Betriebsbudgets.",
      answer: "Zum Lernen empfehlen wir einen kleinen Geschenkeshop, wenn Nachfrage und Budget passen. Er ist eine freiwillige Wahl und keine feste Tutorialvorgabe. Entscheidend ist, dass du den Betrieb vollständig ausstatten und weiter versorgen kannst. Kein Geschäft ist in jedem Spielstand der profitabelste Einstieg.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-customer-capacity", "big-ambitions-employee-scheduling", "big-ambitions-warehouse-setup", "big-ambitions-best-investment"],
      sections: [
        { heading: "Mit dem Tutorial den gesamten Ablauf lernen", paragraphs: [
          "Ein Geschenkeshop führt durch Warenbeschaffung, Auslagen, Kasse, Preise und Schichten. Unsere Empfehlung betrifft diesen überschaubaren Lernablauf und verspricht keine höchste Gewinnspanne.",
          "Lies Uncle Freds aktuelle Aufgabe vor der Anmietung oder Einstellung. Das Tutorial wurde geändert: Der offizielle Bericht zu 1.0 beschreibt Personalaufgaben, die sich beispielsweise an Fitnessstudios und Friseure anpassen. Ein Geschenkeshop ist somit eine Empfehlung, keine feste Vorgabe des heutigen Tutorials.",
        ] },
        { heading: "Alternativen nach Arbeitsaufwand vergleichen", paragraphs: [
          "Vergleiche bei freiem Start beispielsweise Geschenkeshop, Gastronomie oder Café und eine Bürodienstleistung. Beim Einzelhandel stehen Waren und Kasse im Mittelpunkt; bei Essen kommen die benötigten Gerätekategorien hinzu. Im Büro bestimmen Arbeitsplätze, Spezialisten und Kundenauslastung den Plan.",
          "Preislisten und Gewinnbilder aus einem ausgebauten Spielstand ersetzen kein Eröffnungsbudget. Ausgebildetes Personal und etablierte Lieferverträge verändern die Ausgangslage erheblich.",
        ] },
        { heading: "Standort und Reserve vor der Eröffnung prüfen", paragraphs: [
          "Prüfe in Market Insider das richtige Viertel und vergleiche Nachfrage, Konkurrenz und geeignete Immobilien. Hohe Gebäudekapazität allein erzeugt keine Käufer.",
          "Trenne einmalige Einrichtungsausgaben vom laufenden Betrieb. Unsere Empfehlung: keinen Plan umsetzen, der nach dem Möbelkauf kein Geld mehr für Nachschub und Löhne lässt.",
        ], bullets: [
          "1. Vollständige Mindestausstattung im aktuellen Spiel kalkulieren.",
          "2. Anfangsbestand und die nächste Warenbestellung einplanen.",
          "3. Löhne, Miete und weitere laufende Kosten addieren.",
          "4. Geld für Liefer- oder Personalprobleme zurückhalten.",
          "5. Erst eröffnen, wenn Einrichtung und Betrieb finanzierbar sind.",
        ] },
        { heading: "Den ersten Betrieb vor der zweiten Filiale stabilisieren", paragraphs: [
          "Kontrolliere stündliche Kundenzahlen, leere Bestände, Personalwünsche und Ausgaben. Behebe jeweils die konkrete Ursache: Waren nachliefern, Schichten schließen oder Preise und Öffnungszeiten prüfen.",
          "Unsere Empfehlung vor der Expansion ist ein Geschäft, das seine geplanten Verkaufstage ohne dauernde Notkäufe oder deine ständige Kassenarbeit abschließt. Verwaltungsinfrastruktur lohnt sich, wenn sie einen tatsächlichen Arbeitsaufwand löst.",
        ] },
        { heading: "Fragen zum besten Startgeschäft", paragraphs: [
          "Ist der Geschenkeshop immer am profitabelsten? Nein. Er ist eine sinnvolle Lernroute; Ergebnis und Kosten hängen vom Standort ab.",
          "Soll ich einer alten Rangliste folgen? Prüfe ihre Version. Der Entwickler dokumentierte bereits im Juni 2023 erhebliche Änderungen der Geschäftsbalance.",
          "Warum zählt mein Shop nicht für das Tutorial? Vergleiche Geschäftstyp und Gebäudebedingungen mit der aktuellen Aufgabe, bevor du mehr einkaufst.",
        ] },
      ],
      sources: [
        { label: "Offizielle Shopseite: Geschäftsarten und Unternehmensaufbau", href: source.store },
        { label: "Offizieller Änderungsbericht zu 1.0 vom 14. August 2026: dynamische Personalaufgaben", href: source.release },
        { label: "Entwickler, 27. Mai 2023: Ausstattung und Kapazität", href: source.equipment },
        { label: "Entwickler, 13. Januar 2024: Nachfrage und Konkurrenz", href: source.capacity },
        { label: "Entwickler, 13. Juni 2023: geänderte Geschäftsbalance", href: source.balance },
      ],
    },
  ],
  fr: [
    {
      locale: "fr", category: "guides", slug: "big-ambitions-customer-capacity",
      keyword: "Big Ambitions capacité clients",
      title: "Big Ambitions capacité clients : trouver la limite",
      description: "Comprenez la capacité clients de Big Ambitions en comparant bâtiment, équipements et fréquentation horaire avant d’acheter du matériel ou un local plus grand.",
      summary: "Repérez la catégorie d’équipement qui limite le magasin et utilisez les heures de pointe pour décider d’un agrandissement.",
      answer: "La capacité clients de Big Ambitions dépend du bâtiment et de chaque catégorie d’équipement nécessaire. La catégorie la plus faible limite le commerce. Des caisses supplémentaires ne compensent pas des présentoirs insuffisants, et une capacité supérieure ne garantit pas davantage de clients.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-best-starting-business", "big-ambitions-market-insider", "big-ambitions-product-pricing", "big-ambitions-warehouse-setup"],
      sections: [
        { heading: "Comparer le bâtiment et chaque catégorie", paragraphs: [
          "Ouvrez le détail de capacité du commerce dans BizMan. Comparez la limite du bâtiment au total de chaque catégorie nécessaire. Additionner caisses et présentoirs dans un seul chiffre masque le véritable problème.",
          "Exemple fictif : le bâtiment autorise 40 clients, une catégorie en accepte 30 et une autre 50. La limite est alors 30. Porter la première catégorie à 45 laisse le bâtiment limiter l’ensemble à 40. Consultez les valeurs actuelles des objets dans votre partie.",
        ] },
        { heading: "Améliorer uniquement le matériel limitant", paragraphs: [
          "Un produit ajouté au catalogue peut créer une nouvelle catégorie d’équipement à fournir. Revérifiez donc la capacité après toute extension de l’assortiment. Remplir un rayon évite une rupture, mais n’augmente pas nécessairement sa capacité nominale.",
        ], bullets: [
          "1. Relever la catégorie la plus faible et la limite du bâtiment.",
          "2. Vérifier le prix et la capacité du matériel correspondant dans le jeu.",
          "3. Ajouter le matériel nécessaire, son stock et le personnel requis.",
          "4. Relire le détail de capacité avant l’achat suivant.",
        ] },
        { heading: "Observer les heures de pointe", paragraphs: [
          "Dans BizMan > Insights, affichez la veille sur le graphique des clients. Cette vue horaire est recommandée par le développeur. Une moyenne quotidienne faible peut cacher plusieurs heures complètement remplies.",
          "Comparez des journées similaires en notant les pointes, ruptures de stock et stations sans employé. Notre conseil : corriger une seule contrainte, puis comparer les mêmes heures de nouveau.",
        ] },
        { heading: "Distinguer passage, demande et capacité", paragraphs: [
          "Le Traffic Index représente le passage potentiel et non un plafond fixe de clients. Le développeur l’a confirmé en février 2025. Une valeur de 30 ne signifie donc pas exactement 30 clients par heure.",
          "Si le commerce reste calme, vérifiez prix, concurrence, horaires et disponibilité. Un commerce de bijoux peut ne jamais remplir un grand local. Comparez un déménagement lorsque les équipements atteignent déjà la limite du bâtiment et que les pointes la rencontrent régulièrement.",
        ] },
        { heading: "Questions sur la capacité clients", paragraphs: [
          "Une caisse supplémentaire suffit-elle ? Seulement si les caisses limitent réellement le commerce et si la nouvelle station peut fonctionner.",
          "Ajouter un produit peut-il réduire la capacité ? Oui, si sa catégorie d’équipement devient la plus faible.",
          "Faut-il davantage de publicité quand le magasin est plein ? La publicité ne relève pas la limite du bâtiment. Vérifiez d’abord les heures encore disponibles.",
        ] },
      ],
      sources: [
        { label: "Développeur, 13 janvier 2024 : capacité et fréquentation horaire", href: source.capacity },
        { label: "Développeur, 27 mai 2023 : limites des bâtiments et équipements", href: source.equipment },
        { label: "Développeur, 3 mai 2023 : ajout de catégories de produits", href: source.secondary },
        { label: "Développeur, 14 février 2025 : passage et capacité", href: source.traffic },
        { label: "Développeur, 9 avril 2023 : fréquentation d’une bijouterie", href: source.jewelry },
      ],
    },
    {
      locale: "fr", category: "guides", slug: "big-ambitions-employee-scheduling",
      keyword: "Big Ambitions planning des employés",
      title: "Big Ambitions planning des employés : bien répartir",
      description: "Réglez le planning des employés de Big Ambitions selon les jours, heures et exigences de chacun, puis contrôlez le travail déjà effectué après un changement.",
      summary: "Planifiez chaque jour, contrôlez les heures hebdomadaires et comprenez les avertissements qui suivent un changement en cours de semaine.",
      answer: "Fixez les horaires du commerce, puis affectez les employés aux postes nécessaires. Désactivez le planning commun si leurs jours de repos diffèrent. Vérifiez les heures hebdomadaires, les exigences individuelles et le travail déjà effectué avant de modifier une semaine commencée.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-office-requirements", "big-ambitions-customer-capacity", "big-ambitions-best-starting-business", "big-ambitions-logistics-manager"],
      sections: [
        { heading: "Séparer ouverture du commerce et présence d’un employé", paragraphs: [
          "Fermer le commerce un jour affecte toute l’équipe. Pour donner congé à une seule personne, modifiez son affectation, sans changer les jours d’ouverture. Le développeur distingue explicitement ces deux réglages.",
          "Dans un commerce existant, comparez les horaires au graphique des clients. Les ventes supplémentaires attendues le matin ou le soir doivent justifier les salaires correspondants.",
        ] },
        { heading: "Attribuer des jours différents", paragraphs: [
          "Désactivez le planning partagé entre tous les jours lorsque le week-end nécessite une autre équipe. Cliquez ensuite sur le jour à modifier. Le développeur a confirmé cette méthode en janvier 2025.",
        ], bullets: [
          "1. Lire les exigences d’heures, de jours et de créneaux de chaque personne.",
          "2. Désactiver le planning commun si les jours doivent différer.",
          "3. Sélectionner chaque journée et affecter les personnes aux postes.",
          "4. Couvrir les créneaux vides, puis vérifier les totaux hebdomadaires.",
        ] },
        { heading: "Compter les heures déjà travaillées", paragraphs: [
          "Le temps plein est une exigence hebdomadaire. En novembre 2024, le développeur indiquait une plage de 30 à 50 heures ; vérifiez la demande affichée dans votre partie. Huit heures répétées pendant sept jours donnent déjà 56 heures.",
          "Modifier le planning n’efface pas les heures précédentes. Le développeur précise en mai 2025 que cette comptabilité repart le lundi. Examinez aussi les demandes distinctes, comme une semaine de quatre jours, avant d’attribuer un avertissement à un bug.",
        ] },
        { heading: "Contrôler le remplissage automatique et le siège", paragraphs: [
          "Après le remplissage automatique, vérifiez les heures sans couverture et les exigences de chaque employé. L’outil a été remanié selon une réponse officielle d’avril 2025 : les anciens témoignages ne décrivent pas forcément votre version.",
          "Le siège utilise un planning fixe pour ses fonctions de gestion. Si ses horaires sont verrouillés, contrôlez l’affectation à l’entreprise et au bureau. Ajouter une soirée de travail n’est pas la méthode prévue pour activer une place libre.",
        ] },
        { heading: "Questions sur le planning des employés", paragraphs: [
          "Pourquoi une exigence d’heures reste-t-elle insatisfaite ? Vérifiez le travail déjà effectué cette semaine et les demandes concernant jours et créneaux.",
          "Comment libérer le vendredi pour une personne ? Retirez son affectation du vendredi et prévoyez un remplaçant sans fermer l’entreprise.",
          "Quand signaler un problème ? Si une semaine complète avec des exigences respectées montre toujours une incohérence. Joignez les sept jours et la version du jeu.",
        ] },
      ],
      sources: [
        { label: "Développeur, 12 janvier 2025 : modifier les jours séparément", href: source.dailySchedule },
        { label: "Développeur, 11 janvier 2024 : ouverture et affectations individuelles", href: source.employeeSchedule },
        { label: "Développeur, 24 novembre 2024 : heures du temps plein", href: source.fullTime },
        { label: "Développeur, 1er mai 2025 : heures antérieures et lundi", href: source.weeklyHours },
        { label: "Développeur, 1er avril 2025 : nouvel outil de planning", href: source.scheduler },
        { label: "Développeur, 15 avril 2025 : horaires fixes du siège", href: source.hq },
      ],
    },
    {
      locale: "fr", category: "guides", slug: "big-ambitions-product-pricing",
      keyword: "Big Ambitions prix des produits",
      title: "Big Ambitions prix des produits : tester ses tarifs",
      description: "Ajustez les prix des produits de Big Ambitions avec les tarifs locaux, des essais sur un seul article et un suivi des ventes, des achats et de la rentabilité.",
      summary: "Modifiez un produit à la fois et comparez sa contribution après achat, sans confondre prix élevé et bénéfice supérieur.",
      answer: "Testez les prix des produits de Big Ambitions par article et par quartier. Prenez les concurrents comme repère, modifiez un prix à la fois, puis examinez satisfaction et résultat après des journées complètes. Les anciens tableaux de prix maximaux ne garantissent pas le résultat de votre partie.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-purchasing-agent", "big-ambitions-customer-capacity", "big-ambitions-best-investment"],
      sections: [
        { heading: "Partir d’un repère local", paragraphs: [
          "Consultez le prix actuel et les informations sur la concurrence dans BizMan. Le développeur a confirmé en mars 2024 l’affichage du concurrent le moins cher. Ce repère n’oblige pas à vendre moins cher : vos coûts restent déterminants.",
          "Notez le quartier. Avant de reprendre les tarifs d’une autre succursale, testez leur acceptation dans le nouveau secteur.",
        ] },
        { heading: "Tester un seul produit", paragraphs: [
          "La méthode décrite par le développeur consiste à augmenter progressivement un prix et à attendre un ou deux jours avant d’examiner la satisfaction tarifaire dans BizMan > Insights. Modifier toute la liste empêche d’identifier facilement l’article responsable d’une baisse.",
        ], bullets: [
          "1. Noter prix initial, coût d’achat, quantités vendues et satisfaction.",
          "2. Modifier légèrement le tarif du seul produit choisi.",
          "3. Garder horaires, personnel et publicité aussi stables que possible.",
          "4. Comparer ventes et contribution après des journées terminées.",
          "5. Conserver ou annuler le changement avant le prochain essai.",
        ] },
        { heading: "Comparer la contribution après achat", paragraphs: [
          "Pour la marchandise, multipliez les unités vendues par la différence entre prix de vente et coût d’achat unitaire. Cette comparaison précède loyers, salaires et autres dépenses ; elle n’est pas le bénéfice complet du commerce.",
          "Exemple fictif : 100 unités vendues 12 et achetées 7 donnent 500 avant autres frais. À 14, 75 ventes donnent 525. Une baisse du volume peut donc rester avantageuse. Pour les services de bureau, surveillez surtout les salaires nécessaires aux clients supplémentaires.",
        ] },
        { heading: "Contrôler le responsable des prix et les coûts", paragraphs: [
          "Le journal officiel de la version 1.0 ajoute un responsable des prix au siège, capable de modifier les tarifs de tout un quartier. Les employés plus compétents proposent aussi des prix quotidiennement. Vérifiez les commerces concernés et comparez le résultat à votre référence.",
          "Relevez aussi le coût fournisseur. Le développeur relie le prix d’un contrat à l’indice d’importation et à la compétence de l’agent lors de sa création. Un nouveau contrat peut modifier la marge indépendamment du prix de vente.",
          "Dès juin 2023, le développeur signalait que d’anciens tableaux étaient dépassés. Utilisez-les comme références datées et refaites un essai ciblé après un changement de coûts, de quartier ou de réaction des clients.",
        ] },
        { heading: "Questions sur les prix des produits", paragraphs: [
          "Faut-il une satisfaction tarifaire parfaite ? C’est une indication utile, mais comparez aussi les revenus et les coûts.",
          "Pourquoi les ventes baissent-elles ? Contrôlez ruptures, personnel, horaires et concurrence avant de tout attribuer au nouveau prix.",
          "Les succursales doivent-elles partager tous leurs tarifs ? Testez les conditions locales au lieu de supposer une liste universelle.",
        ] },
      ],
      sources: [
        { label: "Journal officiel de la version 1.0, publié le 14 août 2026 : responsable des prix", href: source.release },
        { label: "Développeur, 31 mars 2024 : prix concurrents dans BizMan", href: source.competitors },
        { label: "Développeur, 22 mars 2023 : essais progressifs", href: source.priceTest },
        { label: "Développeur, 15 octobre 2022 : isoler un produit", href: source.onePrice },
        { label: "Développeur, 9–10 avril 2023 : coûts d’importation", href: source.importCosts },
        { label: "Développeur, 4 juin 2023 : anciens tableaux dépassés", href: source.oldPrices },
      ],
    },
    {
      locale: "fr", category: "guides", slug: "big-ambitions-office-requirements",
      keyword: "Big Ambitions exigences des bureaux",
      title: "Big Ambitions exigences des bureaux : préparer les postes",
      description: "Vérifiez les exigences des bureaux de Big Ambitions pour les postes, employés et affectations, puis distinguez le siège des entreprises qui servent des clients.",
      summary: "Validez les postes de travail et les demandes individuelles avant d’ajouter des meubles ou de recruter une grande équipe.",
      answer: "Un bureau nécessite des postes utilisables avec ordinateur et chaise, les toilettes et lavabos requis, ainsi que des employés adaptés et affectés. Vérifiez les exigences de l’entreprise et les demandes personnelles. Le siège gère vos entreprises ; un bureau de services dépend aussi de son marché de clients.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-employee-scheduling", "big-ambitions-purchasing-agent", "big-ambitions-logistics-manager", "big-ambitions-where-to-buy-bathroom-stall"],
      sections: [
        { heading: "Distinguer siège et entreprise de services", paragraphs: [
          "Un cabinet d’avocats facture des clients. Le siège accueille des fonctions de gestion : achats, logistique et ressources humaines. Choisissez cette fonction avant d’équiper les lieux ou de recruter.",
          "Le Traffic Index reste pertinent pour les bureaux de services, selon le développeur en décembre 2025. Pour le siège, comparez surtout les postes utilisables et les équipements demandés qui tiennent dans le local.",
        ] },
        { heading: "Valider un premier poste complet", paragraphs: [
          "Commencez par un bureau, un ordinateur et une chaise correctement reliée. Si l’ordinateur indique une chaise manquante, vérifiez son placement et l’orientation du bureau : le développeur cite ce problème dans son assistance.",
          "Prévoyez toilettes et lavabos. Les notes officielles d’EA 0.9 imposent des sanitaires selon la taille du bureau et précisent qu’il ne gagne pas d’argent sans eux. Consultez les exigences actuelles pour choisir les équipements et quantités nécessaires.",
        ], bullets: [
          "1. Lire les exigences actuelles de l’activité et de l’employé.",
          "2. Installer bureau, ordinateur et chaise dans une disposition valide.",
          "3. Corriger les avertissements, installer les sanitaires requis et préserver l’accès.",
          "4. Affecter une personne adaptée dans le planning.",
          "5. Reproduire seulement le poste dont le fonctionnement est confirmé.",
        ] },
        { heading: "Affecter les personnes au bon ordinateur", paragraphs: [
          "Recruter ne suffit pas à occuper un poste. Vérifiez l’entreprise attribuée à la personne, puis son affectation dans le planning. Parcourez la liste complète des postes et contrôlez le jour sélectionné.",
          "Un cas résolu par le développeur en juin 2025 illustre une confusion : des places libres en bas de liste avaient été prises pour des créneaux de week-end. L’affectation aux bons bureaux a activé les agents d’achat.",
        ] },
        { heading: "Contrôler demandes, plans et limites du siège", paragraphs: [
          "Comparez les meubles demandés avec ceux du poste réellement utilisé. La bonne chaise à un autre bureau ne prouve pas que cette personne dispose de son équipement. Utilisez les informations du poste pour retrouver la bonne combinaison.",
          "Le développeur indique que l’éditeur de plans du menu principal permet de modifier un plan existant. Vérifiez néanmoins le résultat installé et les demandes de votre équipe.",
          "Le siège n’a pas de limite liée à l’accueil de clients : les places de bureau adaptées déterminent l’espace exploitable. Son planning est fixe. Dans un bureau de services, des recrutements supplémentaires doivent en revanche être justifiés par l’activité réelle.",
        ] },
        { heading: "Questions sur les exigences des bureaux", paragraphs: [
          "Pourquoi la chaise n’est-elle pas reconnue ? Vérifiez son rattachement au poste et le sens du bureau.",
          "Un plan termine-t-il toute la configuration ? Il aide à aménager les lieux, mais ne remplace pas la vérification des affectations et demandes individuelles.",
          "Existe-t-il une liste d’achats valable partout ? Non. Le type d’activité, les exigences actuelles et votre personnel déterminent le matériel nécessaire.",
        ] },
      ],
      sources: [
        { label: "Page officielle : fonctions de gestion et siège", href: source.store },
        { label: "Aperçu officiel d’EA 0.9, 12 août 2025 : sanitaires des bureaux", href: source.tutorialUpdate },
        { label: "Développeur, 9 mai 2023 : chaise et orientation du bureau", href: source.chair },
        { label: "Développeur, 17–18 juin 2025 : affectation aux postes", href: source.desk },
        { label: "Développeur, juin 2023 : identifier les équipements du poste", href: source.deskIdentity },
        { label: "Développeur, 15 avril 2025 : capacité du siège", href: source.hq },
        { label: "Développeur, 8 décembre 2025 : passage et bureaux", href: source.officeTraffic },
        { label: "Développeur, 17 février 2026 : modifier les plans de bureaux", href: source.officeBlueprint },
      ],
    },
    {
      locale: "fr", category: "guides", slug: "big-ambitions-best-starting-business",
      keyword: "Big Ambitions meilleur commerce pour débuter",
      title: "Big Ambitions meilleur commerce pour débuter : choisir",
      description: "Choisissez le meilleur commerce pour débuter dans Big Ambitions selon le tutoriel, la demande locale, les équipements, les salaires et votre réserve d’argent.",
      summary: "Envisagez une petite boutique de cadeaux ou comparez quelques activités abordables avec un budget d’ouverture et de fonctionnement.",
      answer: "Pour apprendre, nous recommandons une petite boutique de cadeaux si demande locale et budget le permettent. C’est un choix facultatif, pas une obligation du tutoriel. Retenez une activité que vous pouvez équiper et approvisionner sans vider votre trésorerie. Aucun commerce ne gagne dans toutes les parties.",
      updated: "2026-09-08",
      relatedSlugs: ["big-ambitions-market-insider", "big-ambitions-customer-capacity", "big-ambitions-employee-scheduling", "big-ambitions-warehouse-setup", "big-ambitions-best-investment"],
      sections: [
        { heading: "Apprendre une activité complète avec le tutoriel", paragraphs: [
          "La boutique de cadeaux permet d’apprendre approvisionnement, présentoirs, caisse, prix et planning. Notre recommandation vise ce parcours concret, sans promettre la meilleure marge du jeu.",
          "Lisez la tâche actuelle d’Uncle Fred avant de louer ou de recruter. Le tutoriel a évolué : le journal officiel de la version 1.0 décrit des objectifs de recrutement adaptés notamment aux salles de sport et salons de coiffure. La boutique de cadeaux reste donc notre suggestion, pas un passage imposé.",
        ] },
        { heading: "Comparer les activités par leur fonctionnement", paragraphs: [
          "Pour un départ libre, comparez par exemple cadeaux, restauration ou café et un service de bureau. Le commerce demande stock et caisse ; l’alimentation ajoute ses catégories d’appareils. Un bureau met l’accent sur postes, spécialistes et clients suffisants pour payer les salaires.",
          "Une capture de gros bénéfices dans une partie avancée n’est pas un budget de débutant. Personnel formé et contrats d’approvisionnement établis changent fortement les conditions de départ.",
        ] },
        { heading: "Vérifier le quartier et conserver une réserve", paragraphs: [
          "Dans Market Insider, sélectionnez le bon quartier, puis comparez demande, concurrence et locaux disponibles. Un bâtiment de grande capacité ne crée pas à lui seul des acheteurs.",
          "Séparez les achats d’ouverture des dépenses de fonctionnement. Notre conseil : écartez un plan qui ne laisse plus d’argent pour la prochaine commande et les salaires.",
        ], bullets: [
          "1. Chiffrer l’installation minimale complète dans le jeu actuel.",
          "2. Ajouter le premier stock et la prochaine commande prévue.",
          "3. Compter salaires, loyer et autres dépenses récurrentes.",
          "4. Garder une réserve pour corriger un problème de livraison ou de personnel.",
          "5. Ouvrir seulement lorsque installation et fonctionnement sont finançables.",
        ] },
        { heading: "Stabiliser la première adresse avant d’en ouvrir une autre", paragraphs: [
          "Surveillez clients par heure, ruptures, demandes du personnel et dépenses. Corrigez chaque cause directement : réapprovisionner, couvrir un créneau, ou revoir tarifs et horaires.",
          "Avant l’expansion, nous conseillons un commerce capable d’effectuer ses journées prévues sans achats d’urgence constants ni votre présence permanente en caisse. Ajoutez de la gestion et de la logistique lorsqu’elles répondent à une charge réelle.",
        ] },
        { heading: "Questions sur le premier commerce", paragraphs: [
          "La boutique de cadeaux est-elle toujours la plus rentable ? Non. C’est un parcours d’apprentissage utile ; le résultat dépend des coûts et de l’adresse.",
          "Faut-il suivre un ancien classement ? Vérifiez sa version. Le développeur signalait déjà des changements importants d’équilibrage en juin 2023.",
          "Pourquoi mon commerce ne valide-t-il pas l’objectif ? Comparez son type et son bâtiment aux conditions actuelles avant de continuer à acheter.",
        ] },
      ],
      sources: [
        { label: "Page officielle : activités et développement des entreprises", href: source.store },
        { label: "Journal officiel de la version 1.0, publié le 14 août 2026 : recrutement adapté à l’activité", href: source.release },
        { label: "Développeur, 27 mai 2023 : équipements et capacité", href: source.equipment },
        { label: "Développeur, 13 janvier 2024 : concurrence et demande", href: source.capacity },
        { label: "Développeur, 13 juin 2023 : évolution de la rentabilité", href: source.balance },
      ],
    },
  ],
};
