import type { Locale } from "@/i18n/locales";
import type { Article, ArticleSection } from "./types";
import { frenchKeywords, frenchResearch } from "./fr-content";
import { priorityGuideArticles } from "./priority-guides";
import { growthLogisticsArticles } from "./growth-logistics";
import { growthBusinessArticles } from "./growth-business";
import { germanResearch } from "./de-content";
import { englishMetadata } from "./metadata-en";
import { germanMetadata } from "./metadata-de";
import { frenchMetadata } from "./metadata-fr";

const links = {
  official: "https://www.bigambitionsgame.com/",
  steam: "https://store.steampowered.com/app/1331550/Big_Ambitions/",
  forum: "https://forum.bigambitionsgame.com/",
  guides: "https://steamcommunity.com/app/1331550/guides/",
  news: "https://store.steampowered.com/news/app/1331550",
  roadmap: "https://www.bigambitionsgame.com/roadmap/",
  workshop: "https://steamcommunity.com/workshop/about/?appid=1331550",
  bathroomSteam: "https://steamcommunity.com/app/1331550/discussions/0/574921277455763437/",
  investmentForum: "https://forum.bigambitionsgame.com/t/more-investments-including-shares-of-a-company/84",
} as const;

type Research = {
  keyword: string;
  category: string;
  slug: string;
  answer: string;
  confirmed: string;
  steps: string[];
  caution: string;
  sources: (keyof typeof links)[];
  deAnswer: string;
};

const research: Research[] = [
  { keyword:"big ambitions guide",category:"guides",slug:"big-ambitions-guide",answer:"The safest Big Ambitions route is to stabilize your character, follow the early objectives, check local demand, open a small affordable business, stock and price it carefully, hire cover, and keep a cash reserve before expanding.",confirmed:"Official material describes a progression from limited money and a first job to rented premises, equipment, inventory, employees, logistics, headquarters, imports, property, and investment funds. Health and happiness remain part of the management problem, so a useful guide cannot treat the game as a spreadsheet alone.",steps:["Maintain sleep, food, health, and a usable home base.","Complete the current tutorial objectives before making speculative purchases.","Use Market Insider to compare unmet demand and competition by district.","Choose a small location whose rent, equipment, inventory, and staffing fit your cash.","Automate the first store and retain emergency cash before opening another."],caution:"Older walkthroughs are useful for understanding the overall loop, but interfaces, objectives, prices, and balance may differ in version 1.0. Confirm exact actions in the current F1 help, BizMan, and Market Insider.",sources:["official","steam","guides"],deAnswer:"Der sichere Einstieg besteht darin, zuerst die Bedürfnisse der Figur zu stabilisieren, aktuelle Ziele zu erfüllen, die lokale Nachfrage zu prüfen und nur ein kleines finanzierbares Geschäft zu eröffnen." },
  { keyword:"big ambitions best starting business",category:"guides",slug:"big-ambitions-best-starting-business",answer:"There is no single best starting business for every Big Ambitions save. The best choice is the affordable business with strong unmet local demand, manageable competition, simple inventory, realistic staffing, and enough cash left after opening.",confirmed:"Community discussions often mention gift shops, fast food, and coffee as accessible concepts, while jewelry, clothing, electronics, and hairdressing can require more capital. Those examples are not universal rankings because district demand, competitors, rent, traffic capacity, and version balance change the result.",steps:["Check unmet district demand in Market Insider.","Count direct competitors and compare nearby traffic capacity.","Budget rent, deposits, furniture, equipment, opening inventory, and wages.","Prefer an operation you can staff and supply without exhausting cash.","Make the first location run without your character before opening location two."],caution:"Do not copy a profit ranking without checking the current save. A recommendation from another district, patch, or challenge setup can be wrong for your market.",sources:["guides","steam"],deAnswer:"Es gibt nicht für jeden Spielstand dasselbe beste Startgeschäft. Entscheidend sind ungedeckte Nachfrage, Konkurrenz, Miete, Einrichtung, Personalbedarf und eine ausreichende Geldreserve." },
  { keyword:"big ambitions best investment fund",category:"guides",slug:"big-ambitions-best-investment",answer:"There is no single investment fund that is always best in Big Ambitions. Choose among the bank's current fund options by risk, keep operating cash outside the investment, and favor business expansion when a proven store can use the money more productively.",confirmed:"The official game description confirms investment funds, real estate, and business expansion as separate uses of capital. Official-community material also describes three standard mutual funds with different risk and reward, but no current primary source publishes one permanent winner or guaranteed return.",steps:["Keep enough liquid cash for rent, wages, inventory, logistics, and emergencies.","Open the bank's current investment screen and compare the displayed risk for every fund.","Use a lower-risk choice for money you may need sooner and accept that returns are not guaranteed.","Compare the fund with reinvesting in a business whose demand and capacity are already proven.","Review performance over multiple in-game periods and rebalance rather than chasing one short result."],caution:"Fund names, displayed risk, fees, update intervals, and returns can change with the game version. Do not copy an old percentage or assume the highest-risk fund must produce the best result in your save.",sources:["official","steam","investmentForum"],deAnswer:"Es gibt in Big Ambitions keinen einzelnen Investmentfonds, der immer der beste ist. Vergleiche die aktuellen Fonds nach Risiko, halte Betriebskapital liquide und investiere weiter ins Unternehmen, wenn ein bewährter Standort das Geld produktiver nutzen kann." },
  { keyword:"big ambitions where to buy truck",category:"guides",slug:"big-ambitions-where-to-buy-truck",answer:"Buy a delivery truck from a vehicle dealership shown on the in-game map. Before purchasing, make sure the destination warehouse has a suitable parking slot and that the planned delivery route, capacity, and employee setup justify the vehicle.",confirmed:"The Steam description explicitly confirms that delivery trucks are bought from a dealership and used with warehouse and logistics systems. Community discussion connects vehicles and warehouse operations with Industry City, but a map search is safer than a written street address that may change.",steps:["Open the map and locate the current vehicle dealership.","Check the truck and its capacity in the current dealer interface.","Confirm that your warehouse has a usable vehicle bay.","Buy and collect the vehicle, then bring it to the warehouse.","Assign routes and staffing only after the warehouse link is working."],caution:"Dealer inventory, prices, and exact map labels can change. Use the current map and F1 help rather than relying on an Early Access address or screenshot.",sources:["steam","forum"],deAnswer:"Einen Lieferwagen kaufst du bei einem Fahrzeughändler auf der Spielkarte. Prüfe vorher Stellplatz, Lager, Kapazität, Route und Personal, damit das Fahrzeug tatsächlich eingesetzt werden kann." },
  { keyword:"big ambitions where to buy bathroom stall",category:"guides",slug:"big-ambitions-where-to-buy-bathroom-stall",answer:"Buy the Bathroom Stall at Essentials Appliances in Big Ambitions. Open the store from the map to preview its inventory, or search the exact phrase “Bathroom Stall” in F1 help and follow the linked shop marker.",confirmed:"A Big Ambitions developer directly confirmed in two Steam discussions that Essentials Appliances sells the Bathroom Stall. The exact name matters: a normal Toilet is a different furnishing, and searching only for toilet can send players to the wrong item or store.",steps:["Open BizMan and confirm that the unmet requirement says Bathroom Stall.","Search Bathroom Stall in F1 help using that exact wording.","Click the linked seller or find Essentials Appliances on the map.","Use the blue magnifying-glass inventory preview before travelling.","Buy and place the stall, then return to BizMan to verify the requirement is satisfied."],caution:"The seller is confirmed, but the current price, stock behavior, dimensions, and any version-specific prerequisite can change. Check the live Essentials Appliances inventory and F1 entry instead of relying on an old price or screenshot.",sources:["bathroomSteam","forum"],deAnswer:"Den Bathroom Stall kaufst du in Big Ambitions bei Essentials Appliances. Suche in der F1-Hilfe exakt nach Bathroom Stall oder prüfe das Ladeninventar über die Karte, damit du ihn nicht mit einer normalen Toilette verwechselst." },
  { keyword:"big ambitions how to take courses",category:"guides",slug:"big-ambitions-how-to-take-courses",answer:"A reliable version-1.0 course procedure is not confirmed by the available official material. Older discussions connect school courses with management or office progression, but the current entry point, schedule, cost, and prerequisites must be checked in the live game.",confirmed:"Early Access players discussed schools, courses, HR, and office management across several different versions. That confirms the search intent, not a permanent 1.0 workflow, because objectives and unlock systems may have changed.",steps:["Check current objectives for any school or course requirement.","Search the F1 help for course, school, management, and HR terms.","Inspect the map and any school interface unlocked by story progress.","Verify time, cost, prerequisite, and the exact reward before paying.","If the interface is absent, treat the old instruction as obsolete."],caution:"Course location, hours, fees, and unlocks are To be confirmed. Do not use a fixed Early Access schedule as a current instruction.",sources:["guides","forum"],deAnswer:"Ein verlässlicher Ablauf für Kurse in Version 1.0 ist noch nicht bestätigt. Alte Beiträge verbinden Schule und Kurse mit Managementfunktionen, doch Zugang, Zeit, Kosten und Voraussetzungen müssen im aktuellen Spiel geprüft werden." },
  { keyword:"big ambitions how to get diploma",category:"guides",slug:"big-ambitions-how-to-get-diploma",answer:"There is no reliable official version-1.0 confirmation that a Diploma is a separate obtainable item, qualification, or task reward in Big Ambitions. Check the current F1 help, school interface, objectives, and achievement text before following old instructions.",confirmed:"Search results for this phrase are sparse and mix real-world education pages with old player discussions. The wording may refer to an earlier task, a player shorthand for course completion, or a low-frequency misunderstanding rather than a current item.",steps:["Search F1 help for Diploma and related course terms.","Review the current objective list for education requirements.","Check any unlocked school interface and its reward wording.","Search current achievement text for the same term.","If the term does not exist, use the current course or qualification name instead."],caution:"Graduation conditions, price, duration, and reward are To be confirmed. This page intentionally does not invent a diploma path.",sources:["guides","forum"],deAnswer:"Es gibt keine verlässliche offizielle Bestätigung, dass ein Diploma in Version 1.0 ein eigenes Objekt oder eine Qualifikation ist. Prüfe F1-Hilfe, Schule, Ziele und Erfolge, bevor du alten Anleitungen folgst." },
  { keyword:"big ambitions how to upload images",category:"guides",slug:"big-ambitions-how-to-upload-images",answer:"Use a PNG file in the Windows CustomIcons folder, then refresh and select it from the business customization area in BizMan. The researched path is AppData/LocalLow/Hovgaard Games/Big Ambitions/CustomIcons, but current 1.0 size guidance should be checked in the interface.",confirmed:"Steam and official-forum discussions describe custom business icons through PNG files and the CustomIcons directory. They also distinguish a business logo from billboard, square-sign, and wide-sign artwork, which may use different placement or display rules.",steps:["Prepare a readable PNG with strong contrast.","Place it in AppData/LocalLow/Hovgaard Games/Big Ambitions/CustomIcons.","Open the business in BizMan and enter logo customization.","Refresh the file list, select the image, and save.","If it does not appear, recheck format, save state, and restart the game."],caution:"Older posts disagree between 512×512 and 1024×1024. The best current image size is To be confirmed from the 1.0 prompt or default template; back up saves before changing any related files.",sources:["forum","guides"],deAnswer:"Lege eine PNG-Datei im Windows-Ordner CustomIcons ab und wähle sie anschließend in der Unternehmensanpassung von BizMan. Die genaue optimale Bildgröße muss in Version 1.0 noch geprüft werden." },
  { keyword:"big ambitions similar games",category:"alternatives",slug:"big-ambitions-similar-games",answer:"The most useful Big Ambitions alternatives depend on what you want to preserve: deep company management, open-world life simulation, hands-on shop operation, or office and employee systems. No single alternative reproduces every part of the game.",confirmed:"Steam recommendations and community discussions commonly compare Startup Company, Software Inc., Capitalism, SAELIG, The Guild, and retail-management simulations. Each comparison needs a feature-by-feature explanation because many business games lack direct character control or an open city.",steps:["Choose whether business depth or character life is the priority.","Check whether you want direct shop-floor work or abstract management.","Confirm employee, office, production, and logistics features on the candidate's Steam page.","Check the actual single-player or multiplayer tags.","Compare what the alternative omits as carefully as what it shares."],caution:"A community mention is not a guarantee of identical mechanics. Platform support, multiplayer, romance, and current availability should be verified on each candidate's official store page.",sources:["steam","guides"],deAnswer:"Die beste Alternative hängt davon ab, ob du Unternehmensführung, offene Lebenssimulation, aktive Ladenarbeit oder Personal- und Bürosysteme suchst. Kein einzelnes Spiel bildet alle Elemente von Big Ambitions ab." },
  { keyword:"big ambitions multiplayer alternatives",category:"alternatives",slug:"big-ambitions-multiplayer-alternatives",answer:"Big Ambitions is officially listed as single-player, so players who need co-op or competitive business play should choose a separately verified multiplayer alternative. An unofficial community multiplayer project is not the same as official online support.",confirmed:"The current Steam page marks Big Ambitions as Single-player. Community discussion mentions an unofficial Big Ambitions Online mod project whose developer says it is not affiliated with Hovgaard Games.",steps:["Decide whether you want co-op management or competitive economics.","Verify the multiplayer feature on the alternative game's Steam page.","Check player limits, hosting method, and whether progress is shared.","Separate native multiplayer from third-party mods.","Review current support and update history before buying for a group."],caution:"Do not describe the community multiplayer project as an official mode. Its compatibility, security, and current status are To be confirmed before use.",sources:["steam"],deAnswer:"Big Ambitions ist offiziell als Einzelspieler-Spiel gelistet. Für Koop oder wirtschaftlichen Wettbewerb brauchst du eine separat geprüfte Multiplayer-Alternative; ein Community-Mod ist keine offizielle Online-Funktion." },
  { keyword:"big ambitions romance alternatives",category:"alternatives",slug:"big-ambitions-romance-alternatives",answer:"Big Ambitions does not advertise a deep romance or partner system as a core feature. Players who want business management together with relationship progression should compare life simulations whose official descriptions clearly confirm romance.",confirmed:"Official Big Ambitions material emphasizes business, investment, real estate, health, and happiness rather than dating mechanics. A recommendation therefore needs separate ratings for business depth, life simulation, and actual relationship development.",steps:["Confirm that romance is a real progression system, not decorative dialogue.","Compare the candidate's business or shop-management depth.","Check how much direct character life simulation it includes.","Verify platform, current availability, and relationship restrictions.","Choose based on the balance of romance and management you actually want."],caution:"A game with NPC conversations or marriage decoration should not be presented as a full romance simulation. Candidate features must be checked on official store pages.",sources:["official","steam"],deAnswer:"Big Ambitions bewirbt kein tiefes Liebes- oder Partnersystem als Kernfunktion. Wer Beziehung und Unternehmensführung verbinden möchte, sollte Lebenssimulationen mit offiziell bestätigter Romanze vergleichen." },
  { keyword:"big ambitions 1.0 release date",category:"updates",slug:"big-ambitions-1-0-release-date",answer:"Big Ambitions version 1.0 released on August 28, 2026. The game first entered Steam Early Access on March 10, 2023, so the 2023 date should not be presented as the full-release date.",confirmed:"The Steam store and official project material distinguish the Early Access period from the 1.0 launch. Release coverage also describes new district or life content and changes to banking and management, but feature details should be read in the official launch announcement.",steps:["Use March 10, 2023 for the Early Access launch.","Use August 28, 2026 for the version-1.0 release.","Check Steam News for the final launch change list.","Separate launch features from later patches.","Do not reuse outdated pages that call 2023 the final release."],caution:"Any platform release beyond Windows and macOS on Steam is To be confirmed. A 1.0 date does not imply an announced console or mobile version.",sources:["official","steam","news"],deAnswer:"Big Ambitions 1.0 erschien am 28. August 2026. Der 10. März 2023 war der Start im Steam Early Access und darf nicht als Datum der Vollversion bezeichnet werden." },
  { keyword:"big ambitions next update",category:"updates",slug:"big-ambitions-next-update",answer:"The next Big Ambitions update has no confirmed date in the researched material. Treat only the official roadmap, Steam News, the developer website, or a direct developer announcement as confirmation.",confirmed:"Version 1.0 released on August 28, 2026, making older roadmap predictions especially easy to misread. A useful update page must separate already released work, confirmed plans without dates, and player suggestions.",steps:["Check the official roadmap first.","Compare it with the newest Steam News post.","Look for a date stated directly by Hovgaard Games.","Label undated plans separately from dated releases.","Replace the old next-update entry when a newer official announcement appears."],caution:"Community wish lists, mod features, and speculation are not official plans. Next release date: To be confirmed.",sources:["roadmap","news","official"],deAnswer:"Für das nächste Update von Big Ambitions ist im geprüften Material kein bestätigtes Datum genannt. Als Bestätigung gelten nur Roadmap, Steam-News, Entwicklerwebsite oder direkte Aussagen von Hovgaard Games." },
  { keyword:"big ambitions patch notes",category:"updates",slug:"big-ambitions-patch-notes",answer:"Use Big Ambitions Steam News and official developer posts as the factual patch-note record. Organize each version by release date, new features, balance changes, bug fixes, save compatibility, and known issues without mixing in community guesses.",confirmed:"Older Early Access notes remain useful history, but the default view should prioritize version 1.0 and later updates. Steam Community posts can reveal player impact, yet they should be labeled separately from the official change list.",steps:["Record the exact version and official release date.","Summarize features, balance, and fixes in separate groups.","Copy no claim that is absent from the official announcement.","Add save compatibility and known issues only when confirmed.","Link the original official post for context."],caution:"A reported player problem is not automatically an acknowledged known issue. Future patch content and dates remain To be confirmed until published officially.",sources:["news","official","steam"],deAnswer:"Die verlässliche Grundlage für Patch Notes sind Steam-News und offizielle Entwicklerbeiträge. Trenne Version, Datum, neue Funktionen, Balance, Fehlerbehebungen, Speicherkompatibilität und bekannte Probleme klar voneinander." },
  { keyword:"big ambitions ps5",category:"platforms",slug:"big-ambitions-ps5",answer:"There is currently no confirmed Big Ambitions PS5 version or official PlayStation Store listing. The verified release platforms are Windows and macOS through Steam, and no console date should be inferred from controller support or player requests.",confirmed:"The official website and Steam page provide the verified PC and Mac release information but no PS5 product page. Without an official PlayStation listing or developer announcement, price, pre-order, features, and release date remain unconfirmed.",steps:["Check the official Big Ambitions website.","Check Steam News and the public roadmap.","Look for a real PlayStation Store product page.","Require a direct developer announcement before publishing a date.","Ignore controller-layout evidence as proof of a console build."],caution:"PS5 version, price, pre-order, and release date: To be confirmed. Do not download or buy unofficial products claiming to be a console release.",sources:["official","steam","roadmap"],deAnswer:"Derzeit gibt es keine bestätigte PS5-Version und keinen offiziellen PlayStation-Store-Eintrag für Big Ambitions. Verifiziert sind Windows und macOS über Steam; ein Konsolentermin darf nicht vermutet werden." },
  { keyword:"big ambitions mobile",category:"platforms",slug:"big-ambitions-mobile",answer:"There is currently no official Big Ambitions mobile version for Android or iOS. The verified platforms are Windows and macOS on Steam, and remote streaming to a phone is not the same as a native mobile release.",confirmed:"Neither the official website nor the Steam store provides a formal Android or iOS product listing. Claims about mobile APK downloads therefore do not establish an official release.",steps:["Check Hovgaard Games and the official Big Ambitions website.","Require a verified App Store or Google Play listing.","Distinguish Steam remote streaming from a native app.","Avoid APK files distributed by unknown sites.","Wait for an official platform announcement before publishing a date."],caution:"Android version, iOS version, mobile price, and release date: To be confirmed. Unknown APK files may be unsafe and are not recommended.",sources:["official","steam"],deAnswer:"Eine offizielle Android- oder iOS-Version von Big Ambitions ist derzeit nicht bestätigt. Steam-Streaming auf ein Mobilgerät ist keine native mobile Veröffentlichung." },
  { keyword:"big ambitions mods",category:"mods",slug:"big-ambitions-mods",answer:"Use the Big Ambitions Steam Workshop for current mods and enable subscribed content through the game's supported menu flow. Check version compatibility, back up saves, record enabled items, and disable all mods first when diagnosing a crash.",confirmed:"The researched Steam Workshop material shows that Big Ambitions uses Workshop content for mods and building layouts. Mods and Blueprints are different: mods change or extend behavior, while Blueprints store reusable interiors and use an installation workflow.",steps:["Open the official Big Ambitions Steam Workshop.","Read the item description, required dependencies, and current version notes.","Subscribe and enable the mod from the game's menu.","Back up the save and test one change at a time.","After a crash, disable all mods and restore them individually."],caution:"Avoid unknown executable downloads and verify Workshop compatibility after game updates. A popular subscription count is not proof that a mod is safe for the current version.",sources:["workshop","steam","forum"],deAnswer:"Nutze den offiziellen Steam Workshop für Mods von Big Ambitions. Prüfe Version und Abhängigkeiten, sichere Spielstände, notiere aktive Mods und deaktiviere bei Abstürzen zuerst alle Erweiterungen." },
  { keyword:"big ambitions blueprints",category:"mods",slug:"big-ambitions-blueprints",answer:"Big Ambitions Blueprints save and reuse interior layouts for businesses, apartments, or warehouses. Create or save them through the Blueprint Creator or interior-design flow, then install a compatible layout through the correct in-game installation company.",confirmed:"Steam Workshop and community guides describe blueprints as layouts rather than code mods. A blueprint must match the property type, building code, and available size, and a Workshop subscription still needs to synchronize with the in-game library.",steps:["Create or save a layout from the supported blueprint interface.","Subscribe to a Workshop blueprint from a trusted listing.","Synchronize it with the in-game library.","Confirm property type, building code, and size compatibility.","Use the correct interior installation company to apply it."],caution:"Older layouts may depend on outdated game versions or mods. If a blueprint does not appear, check synchronization, compatibility, installer choice, and dependencies before changing the save.",sources:["workshop","guides"],deAnswer:"Blueprints speichern und wiederverwenden Innenraumlayouts für Geschäfte, Wohnungen oder Lager. Sie müssen zu Immobilientyp, Gebäudecode und Größe passen und über den richtigen Einrichtungsbetrieb installiert werden." },
  { keyword:"big ambitions review",category:"reviews",slug:"big-ambitions-review",answer:"Big Ambitions is best suited to players who enjoy growing from hands-on work into systems, staffing, logistics, investment, and executive management. Its appeal is the visible business journey; common reservations concern repetition, later pacing, employee management, and balance.",confirmed:"The Steam page showed a Very Positive English review summary in the research snapshot dated August 31, 2026. Exact review counts and percentages change continuously, so this page focuses on recurring themes rather than freezing those numbers as permanent facts.",steps:["Judge the business and automation depth first.","Decide whether direct city movement adds immersion or repetition for you.","Consider how much employee and logistics management you want.","Read current performance and patch reports for your hardware.","Compare the game with business simulations, not action open worlds."],caution:"Review totals and recent percentages are time-sensitive and should be checked live on Steam. This independent guide does not convert a changing score into a permanent rating.",sources:["steam","official"],deAnswer:"Big Ambitions passt besonders zu Spielern, die den Weg von eigener Arbeit zu Personal, Logistik, Investments und Unternehmensführung mögen. Kritik betrifft häufig Wiederholungen, spätes Tempo, Personalverwaltung und Balance." },
  { keyword:"big ambitions crashes",category:"troubleshooting",slug:"big-ambitions-crashes",answer:"For Big Ambitions crashes, check system requirements, update the operating system and graphics driver, verify Steam files, disable every mod, and test a clean launch before changing saves or configuration. Back up data before clearing anything.",confirmed:"Public reports frequently mention startup failures or long shader-compilation stages. Community-tested launch options can reduce quality and use a low-resolution window, but that is a troubleshooting experiment rather than an official guaranteed fix.",steps:["Compare the computer with the current Steam minimum requirements.","Update the graphics driver and operating system.","Use Steam to verify installed game files.","Disable all mods and test a clean or backed-up save.","Try low-quality windowed launch options only as a temporary diagnostic.","Collect logs, version, hardware, and reproduction steps for official support."],caution:"The researched community launch string is -screen-quality Low -screen-fullscreen 0 -screen-width 1024 -screen-height 768. Back up saves first; do not delete configuration or caches without a recoverable copy.",sources:["steam","forum"],deAnswer:"Bei Abstürzen prüfst du zuerst Anforderungen, System und Grafiktreiber, verifizierst Steam-Dateien und deaktivierst alle Mods. Teste sauber und sichere Daten, bevor du Konfigurationen oder Caches veränderst." },
  { keyword:"big ambitions water cooler",category:"guides",slug:"big-ambitions-water-cooler",answer:"A current, officially documented Big Ambitions water-cooler location, seller, price, or business requirement could not be confirmed from the researched sources. Check the exact item name in F1 help and the live BizMan requirement before buying a similarly named furnishing.",confirmed:"The official Steam description confirms that businesses use placeable furnishings and equipment, but it does not identify a Water Cooler or publish a permanent seller and price. Search results also mix this phrase with unrelated games, so those answers must not be imported into a Big Ambitions guide.",steps:["Read the exact unmet item name in BizMan.","Search F1 help for Water Cooler and nearby terms such as drinks or office equipment.","Use the item entry to identify any current seller.","Check the live store inventory rather than an old screenshot.","Place the item and confirm whether BizMan marks the requirement as satisfied."],caution:"Water Cooler availability, seller, price, size, and business effect are To be confirmed in the current build. Do not treat information about the water cooler in another game as evidence for Big Ambitions.",sources:["official","steam","forum"],deAnswer:"Für einen Wasserspender in Big Ambitions konnten weder Händler noch Preis, Standort oder Geschäftseffekt aktuell offiziell bestätigt werden. Prüfe den exakten Gegenstand in der F1-Hilfe und die Anforderung in BizMan." },
  { keyword:"big ambitions ai music",category:"media",slug:"big-ambitions-ai-music",answer:"There is no verified official statement in the researched material confirming that Big Ambitions uses AI-generated music. An official community response says the radio advertising jingles are original and the in-game music is licensed, which does not by itself establish how every track was produced.",confirmed:"A Hovgaard Games community representative stated that the radio ad jingles are original and all music in the game is licensed for the game and for streaming. The researched official store and developer pages do not label the soundtrack as AI-generated.",steps:["Separate music licensing from the method used to create a track.","Check the current credits and official soundtrack information.","Look for a direct statement from Hovgaard Games or the credited artist.","Treat social posts and detection tools as leads rather than proof.","Update the conclusion only when a primary source identifies the production method."],caution:"Whether any specific track used generative AI is To be confirmed. A licensed track can be human-made or produced with different tools, so licensing status cannot prove or disprove AI use.",sources:["official","steam","forum"],deAnswer:"Es gibt in den geprüften Quellen keine bestätigte offizielle Aussage, dass Big Ambitions KI-generierte Musik verwendet. Bestätigt sind originäre Radio-Jingles und für Spiel sowie Streaming lizenzierte Musik." },
  { keyword:"big ambitions music",category:"media",slug:"big-ambitions-music",answer:"Big Ambitions includes licensed in-game music and original radio advertising jingles, and it supports local MP3 files through a separate custom radio station. Add MP3 files directly to the configured music folder, then select the custom station on an in-game radio.",confirmed:"An official community response says the music is licensed for use in the game and streaming, although automated copyright flags may still occur. Developer replies also confirm that local MP3 tracks play on their own station and that the station appears after compatible files are added.",steps:["Open Options and then Audio to find the local-music folder setting.","Place MP3 files directly in the selected folder without relying on subfolders.","Return to the game and turn on a radio or compatible speaker.","Switch to the local or custom station rather than the default soundtrack station.","If it is missing, verify file type and folder placement before reporting a bug."],caution:"The complete current soundtrack list and publisher ownership for every individual track are To be confirmed. Streaming is permitted according to the official community response, but automated claims may still need to be disputed with the rights holder.",sources:["forum","steam"],deAnswer:"Big Ambitions enthält lizenzierte Spielmusik und eigene Radio-Werbejingles. Eigene MP3-Dateien können über einen separaten lokalen Radiosender abgespielt werden, nachdem sie direkt im konfigurierten Musikordner liegen." },
  { keyword:"big ambitions life sim game",category:"alternatives",slug:"big-ambitions-life-sim-game",answer:"Big Ambitions is a business simulation with life-simulation systems, not a pure everyday-life simulator. The player manages sleep, food, health, happiness, housing, travel, and purchases while building shops, offices, logistics, property, and investments across New York.",confirmed:"The official Steam description calls Big Ambitions a role-playing business simulation and explicitly says the character must interact with the world to survive and succeed. Steam also lists Life Sim among its popular user-defined tags while the core description remains focused on entrepreneurship.",steps:["Expect business growth to remain the main progression loop.","Manage personal needs because they affect the character operating that business.","Use apartments, transport, stores, and city services as functional systems.","Compare it with pure life sims based on relationships and domestic depth separately.","Use the official feature list before assuming a particular life-sim mechanic exists."],caution:"The life-sim label does not confirm deep romance, family, aging, multiplayer, or every feature associated with other life simulators. Those mechanics must be verified individually.",sources:["official","steam"],deAnswer:"Big Ambitions ist eine Wirtschaftssimulation mit Lebenssimulations-Systemen, keine reine Alltagssimulation. Schlaf, Nahrung, Gesundheit, Glück, Wohnen und Wege begleiten den Aufbau von Unternehmen, Logistik und Investments." },
  { keyword:"big ambitions uniform",category:"guides",slug:"big-ambitions-uniform",answer:"Big Ambitions supports employee uniforms, but the exact current assignment controls and available clothing colors should be checked in the live employee-management interface. Older official-forum replies say uniforms were implemented in Beta 8 and later clothing choices expanded during Early Access.",confirmed:"The official community forum marks the original staff-uniform suggestion as implemented in Beta 8. A later implemented-suggestions thread reports additional clothing and uniform options in the EA 0.8 experimental build, while players also documented limits in matching colors across clothing types.",steps:["Open BizMan and select the relevant business or employee group.","Look for the current uniform or clothing assignment control.","Choose only options available to that employee model and role.","Check the result during an active shift inside the business.","Revisit the menu after updates because colors and clothing choices can change."],caution:"The exact version-1.0 menu path, full clothing list, color compatibility, and whether a logo can appear on uniforms are To be confirmed. The old suggestion that a store logo might be added was an idea, not proof of that feature.",sources:["forum","steam"],deAnswer:"Big Ambitions unterstützt Mitarbeiteruniformen. Den aktuellen Menüpfad und die verfügbaren Kleidungsfarben solltest du direkt in der Mitarbeiterverwaltung prüfen; ältere offizielle Forenbeiträge bestätigen die Einführung und spätere Erweiterungen." },
  { keyword:"big ambitions multiplayer",category:"platforms",slug:"big-ambitions-multiplayer",answer:"Big Ambitions does not currently offer official multiplayer or co-op; Steam lists the game as single-player. Older developer comments discussed multiplayer as a possible post-release idea, but they are not a release announcement, roadmap commitment, or confirmed date.",confirmed:"The current Steam feature list identifies Single-player and does not list online co-op, LAN co-op, or multiplayer. In the official community forum, the developer described multiplayer as a major rebuild and acknowledged player interest without confirming implementation.",steps:["Check the current Steam feature list for any platform-status change.","Review the official roadmap and newest Steam News posts.","Require a direct Hovgaard Games announcement before treating multiplayer as planned.","Distinguish official support from third-party community projects.","Do not buy or download an unofficial tool expecting native co-op compatibility."],caution:"Official multiplayer, co-op, player count, networking model, and release date are To be confirmed. Past statements about what might happen after release are not a promise that the feature will ship.",sources:["steam","roadmap","forum"],deAnswer:"Big Ambitions bietet derzeit keinen offiziellen Mehrspieler- oder Koop-Modus; Steam führt das Spiel als Einzelspieler. Ältere Entwicklerkommentare waren Überlegungen und keine bestätigte Ankündigung oder Terminplanung." },
];

function makeTitle(keyword: string): string {
  keyword = keyword.replace(/^big ambitions/i, "Big Ambitions");
  let title = `${keyword} — Verified Guide`;
  if (title.length < 40) title += " for Players";
  if (title.length > 60) title = `${keyword} Guide`;
  return title;
}

function makeFrenchTitle(keyword: string): string {
  let title = `${keyword} — Guide vérifié`;
  if (title.length < 40) title = `${keyword} — Guide complet et vérifié`;
  if (title.length > 60) title = `${keyword} — Guide`;
  return title;
}

function makeDescription(keyword: string, answer: string): string {
  const base = `${keyword}: ${answer} This guide uses verified sources and marks unconfirmed details clearly.`;
  if (base.length <= 160 && base.length >= 140) return base;
  if (base.length < 140) return `${base.slice(0,-1)} for current players.`;
  const sliced = base.slice(0, 159);
  const boundary = sliced.lastIndexOf(" ");
  return `${sliced.slice(0, boundary)}.`;
}

function englishSections(item: Research): ArticleSection[] {
  return [
    { heading: "What you need to know", paragraphs: [item.confirmed] },
    { heading: "Steps to follow", paragraphs: [], bullets: item.steps },
    { heading: "Version notes and limitations", paragraphs: [item.caution] },
    { heading: "Your next step", paragraphs: [item.answer] },
  ];
}

function germanSections(item: Research): ArticleSection[] {
  const content = germanResearch[item.slug];
  return [
    { heading: "Was du wissen solltest", paragraphs: [content?.confirmed ?? item.deAnswer] },
    { heading: "Schritt für Schritt", paragraphs: [], bullets: content?.steps ?? [] },
    { heading: "Version und Einschränkungen", paragraphs: [content?.caution ?? "Die Angaben zur aktuellen Spielversion müssen noch bestätigt werden."] },
    { heading: "Dein nächster Schritt", paragraphs: [item.deAnswer] },
  ];
}

function frenchSections(item: Research): ArticleSection[] {
  const content = frenchResearch[item.slug];
  return [
    { heading: "Réponse directe", paragraphs: [content.confirmed] },
    { heading: "Procédure recommandée", paragraphs: [], bullets: content.steps },
    { heading: "Version et limites", paragraphs: [content.caution] },
    { heading: "Prochaine étape", paragraphs: [content.answer] },
  ];
}

const sourceLabels: Record<keyof typeof links, Record<Locale, string>> = {
  official: { en: "Official Big Ambitions website", de: "Offizielle Website von Big Ambitions", fr: "Site officiel de Big Ambitions" },
  steam: { en: "Big Ambitions on Steam", de: "Big Ambitions auf Steam", fr: "Big Ambitions sur Steam" },
  news: { en: "Official Steam News", de: "Offizielle Steam-Neuigkeiten", fr: "Actualités Steam officielles" },
  roadmap: { en: "Official roadmap", de: "Offizieller Entwicklungsplan", fr: "Feuille de route officielle" },
  workshop: { en: "Steam Workshop", de: "Steam Workshop", fr: "Atelier Steam" },
  forum: { en: "Official forum", de: "Offizielles Forum", fr: "Forum officiel" },
  bathroomSteam: { en: "Steam discussion: Bathroom Stall", de: "Steam-Diskussion: Toilettenkabine", fr: "Discussion Steam : cabine de toilettes" },
  investmentForum: { en: "Official forum: investment funds", de: "Offizielles Forum: Investmentfonds", fr: "Forum officiel : fonds d’investissement" },
  guides: { en: "Steam Community Guides", de: "Anleitungen der Steam-Community", fr: "Guides de la communauté Steam" },
};

function createArticle(item: Research, locale: Locale): Article {
  const french = frenchResearch[item.slug];
  const metadata = { en: englishMetadata, de: germanMetadata, fr: frenchMetadata }[locale][item.slug];
  const answer = locale === "en" ? item.answer : locale === "de" ? item.deAnswer : french.answer;
  const keyword = locale === "fr" ? frenchKeywords[item.slug] : locale === "de" ? (germanResearch[item.slug]?.keyword ?? item.keyword) : item.keyword;
  return {
    locale,
    keyword,
    category:item.category,
    slug:item.slug,
    title: metadata?.title ?? (locale === "en" ? makeTitle(item.keyword) : locale === "de" ? `${keyword} — ${keyword.length < 29 ? "Anleitung für Spieler" : "Anleitung"}` : makeFrenchTitle(keyword)),
    description: metadata?.description ?? makeDescription(keyword,answer),
    summary:answer,
    answer,
    updated: "2026-08-31",
    modified: "2026-09-08",
    sections:locale === "en" ? englishSections(item) : locale === "de" ? germanSections(item) : frenchSections(item),
    sources: item.sources.map((key) => ({ label: sourceLabels[key][locale], href: links[key] })),
  };
}

function buildArticles(locale: Locale): Article[] {
  const merged = new Map(research.map((item) => [item.slug, createArticle(item, locale)]));
  for (const article of [...priorityGuideArticles[locale], ...growthLogisticsArticles[locale], ...growthBusinessArticles[locale]]) {
    merged.set(article.slug, article);
  }
  return [...merged.values()];
}

const articles: Record<Locale, Article[]> = { en: buildArticles("en"), de: buildArticles("de"), fr: buildArticles("fr") };

export function getArticles(locale: Locale): Article[] { return articles[locale]; }
export function getArticle(locale: Locale, slug: string): Article | undefined { return articles[locale].find((article)=>article.slug === slug); }
export function getCategories(locale: Locale): string[] { return [...new Set(articles[locale].map((article)=>article.category))]; }
