import type { Locale } from "@/i18n/locales";
import type { Article, ArticleSection } from "./types";
import { frenchKeywords, frenchResearch } from "./fr-content";

const links = {
  official: "https://www.bigambitionsgame.com/",
  steam: "https://store.steampowered.com/app/1331550/Big_Ambitions/",
  forum: "https://forum.bigambitionsgame.com/",
  guides: "https://steamcommunity.com/app/1331550/guides/",
  news: "https://store.steampowered.com/news/app/1331550",
  roadmap: "https://www.bigambitionsgame.com/roadmap/",
  workshop: "https://steamcommunity.com/workshop/about/?appid=1331550",
} as const;

type Research = {
  keyword: string;
  category: string;
  slug: string;
  answer: string;
  confirmed: string;
  steps: string[];
  caution: string;
  sources: (keyof typeof links)[];
  deAnswer: string;
};

const research: Research[] = [
  { keyword:"big ambitions guide",category:"guides",slug:"big-ambitions-guide",answer:"The safest Big Ambitions route is to stabilize your character, follow the early objectives, check local demand, open a small affordable business, stock and price it carefully, hire cover, and keep a cash reserve before expanding.",confirmed:"Official material describes a progression from limited money and a first job to rented premises, equipment, inventory, employees, logistics, headquarters, imports, property, and investment funds. Health and happiness remain part of the management problem, so a useful guide cannot treat the game as a spreadsheet alone.",steps:["Maintain sleep, food, health, and a usable home base.","Complete the current tutorial objectives before making speculative purchases.","Use Market Insider to compare unmet demand and competition by district.","Choose a small location whose rent, equipment, inventory, and staffing fit your cash.","Automate the first store and retain emergency cash before opening another."],caution:"Older walkthroughs are useful for understanding the overall loop, but interfaces, objectives, prices, and balance may differ in version 1.0. Confirm exact actions in the current F1 help, BizMan, and Market Insider.",sources:["official","steam","guides"],deAnswer:"Der sichere Einstieg besteht darin, zuerst die Bedürfnisse der Figur zu stabilisieren, aktuelle Ziele zu erfüllen, die lokale Nachfrage zu prüfen und nur ein kleines finanzierbares Geschäft zu eröffnen." },
  { keyword:"big ambitions best starting business",category:"guides",slug:"big-ambitions-best-starting-business",answer:"There is no single best starting business for every Big Ambitions save. The best choice is the affordable business with strong unmet local demand, manageable competition, simple inventory, realistic staffing, and enough cash left after opening.",confirmed:"Community discussions often mention gift shops, fast food, and coffee as accessible concepts, while jewelry, clothing, electronics, and hairdressing can require more capital. Those examples are not universal rankings because district demand, competitors, rent, traffic capacity, and version balance change the result.",steps:["Check unmet district demand in Market Insider.","Count direct competitors and compare nearby traffic capacity.","Budget rent, deposits, furniture, equipment, opening inventory, and wages.","Prefer an operation you can staff and supply without exhausting cash.","Make the first location run without your character before opening location two."],caution:"Do not copy a profit ranking without checking the current save. A recommendation from another district, patch, or challenge setup can be wrong for your market.",sources:["guides","steam"],deAnswer:"Es gibt nicht für jeden Spielstand dasselbe beste Startgeschäft. Entscheidend sind ungedeckte Nachfrage, Konkurrenz, Miete, Einrichtung, Personalbedarf und eine ausreichende Geldreserve." },
  { keyword:"big ambitions best investment",category:"guides",slug:"big-ambitions-best-investment",answer:"Big Ambitions has no officially confirmed investment that is always best. Reinvesting in a proven business usually supports active early growth, while property and investment funds make more sense after stable operations can absorb lower liquidity and longer payback periods.",confirmed:"The official game description confirms business expansion, real estate, and investment funds as separate uses of capital. It does not publish a permanent highest-return choice, and community advice consistently depends on the save, current market, and version balance.",steps:["Measure whether an existing location still has profitable capacity to add.","Compare the cash return with the management work required.","Keep operating and emergency cash outside long-term investments.","Use property or funds only when core businesses no longer need the same capital.","Review results over time instead of judging one short period."],caution:"Exact returns can change with balance updates and save conditions. Treat fixed percentages or universal asset rankings from old posts as unconfirmed until checked in the current game.",sources:["official","steam"],deAnswer:"Eine dauerhaft beste Anlage ist offiziell nicht bestätigt. Frühes Kapital ist oft in bewährten Betrieben produktiver; Immobilien und Fonds passen eher zu einem bereits stabilen Cashflow." },
  { keyword:"big ambitions where to buy truck",category:"guides",slug:"big-ambitions-where-to-buy-truck",answer:"Buy a delivery truck from a vehicle dealership shown on the in-game map. Before purchasing, make sure the destination warehouse has a suitable parking slot and that the planned delivery route, capacity, and employee setup justify the vehicle.",confirmed:"The Steam description explicitly confirms that delivery trucks are bought from a dealership and used with warehouse and logistics systems. Community discussion connects vehicles and warehouse operations with Industry City, but a map search is safer than a written street address that may change.",steps:["Open the map and locate the current vehicle dealership.","Check the truck and its capacity in the current dealer interface.","Confirm that your warehouse has a usable vehicle bay.","Buy and collect the vehicle, then bring it to the warehouse.","Assign routes and staffing only after the warehouse link is working."],caution:"Dealer inventory, prices, and exact map labels can change. Use the current map and F1 help rather than relying on an Early Access address or screenshot.",sources:["steam","forum"],deAnswer:"Einen Lieferwagen kaufst du bei einem Fahrzeughändler auf der Spielkarte. Prüfe vorher Stellplatz, Lager, Kapazität, Route und Personal, damit das Fahrzeug tatsächlich eingesetzt werden kann." },
  { keyword:"big ambitions where to buy bathroom stall",category:"guides",slug:"big-ambitions-where-to-buy-bathroom-stall",answer:"The current version's exact bathroom-stall seller still needs confirmation in the in-game F1 item help. A Bathroom Stall is not necessarily the same item as a normal Toilet, so search the exact requirement shown in BizMan before buying furniture.",confirmed:"Community reports indicate that some office-style businesses require a Bathroom Stall and Sink, and players regularly confuse the stall with the ordinary toilet. Public discussion does not provide a sufficiently reliable version-1.0 store name to publish as fact.",steps:["Open BizMan and read the exact unmet facility name.","Open F1 help and search for Bathroom Stall, not only Toilet.","Use the item entry to identify the current seller and map location.","Buy the exact item and place it inside the compatible property.","Return to BizMan and verify that the requirement changes to satisfied."],caution:"The often-repeated community price and older seller locations are patch-sensitive, so they are not treated as fixed facts here. Seller and current cost: To be confirmed in version 1.0.",sources:["forum","guides"],deAnswer:"Der genaue Händler für den Bathroom Stall muss in Version 1.0 noch im F1-Hilfesystem bestätigt werden. Suche nach dem exakten BizMan-Bedarf und verwechsle ihn nicht mit einer normalen Toilette." },
  { keyword:"big ambitions how to take courses",category:"guides",slug:"big-ambitions-how-to-take-courses",answer:"A reliable version-1.0 course procedure is not confirmed by the available official material. Older discussions connect school courses with management or office progression, but the current entry point, schedule, cost, and prerequisites must be checked in the live game.",confirmed:"Early Access players discussed schools, courses, HR, and office management across several different versions. That confirms the search intent, not a permanent 1.0 workflow, because objectives and unlock systems may have changed.",steps:["Check current objectives for any school or course requirement.","Search the F1 help for course, school, management, and HR terms.","Inspect the map and any school interface unlocked by story progress.","Verify time, cost, prerequisite, and the exact reward before paying.","If the interface is absent, treat the old instruction as obsolete."],caution:"Course location, hours, fees, and unlocks are To be confirmed. Do not use a fixed Early Access schedule as a current instruction.",sources:["guides","forum"],deAnswer:"Ein verlässlicher Ablauf für Kurse in Version 1.0 ist noch nicht bestätigt. Alte Beiträge verbinden Schule und Kurse mit Managementfunktionen, doch Zugang, Zeit, Kosten und Voraussetzungen müssen im aktuellen Spiel geprüft werden." },
  { keyword:"big ambitions how to get diploma",category:"guides",slug:"big-ambitions-how-to-get-diploma",answer:"There is no reliable official version-1.0 confirmation that a Diploma is a separate obtainable item, qualification, or task reward in Big Ambitions. Check the current F1 help, school interface, objectives, and achievement text before following old instructions.",confirmed:"Search results for this phrase are sparse and mix real-world education pages with old player discussions. The wording may refer to an earlier task, a player shorthand for course completion, or a low-frequency misunderstanding rather than a current item.",steps:["Search F1 help for Diploma and related course terms.","Review the current objective list for education requirements.","Check any unlocked school interface and its reward wording.","Search current achievement text for the same term.","If the term does not exist, use the current course or qualification name instead."],caution:"Graduation conditions, price, duration, and reward are To be confirmed. This page intentionally does not invent a diploma path.",sources:["guides","forum"],deAnswer:"Es gibt keine verlässliche offizielle Bestätigung, dass ein Diploma in Version 1.0 ein eigenes Objekt oder eine Qualifikation ist. Prüfe F1-Hilfe, Schule, Ziele und Erfolge, bevor du alten Anleitungen folgst." },
  { keyword:"big ambitions how to upload images",category:"guides",slug:"big-ambitions-how-to-upload-images",answer:"Use a PNG file in the Windows CustomIcons folder, then refresh and select it from the business customization area in BizMan. The researched path is AppData/LocalLow/Hovgaard Games/Big Ambitions/CustomIcons, but current 1.0 size guidance should be checked in the interface.",confirmed:"Steam and official-forum discussions describe custom business icons through PNG files and the CustomIcons directory. They also distinguish a business logo from billboard, square-sign, and wide-sign artwork, which may use different placement or display rules.",steps:["Prepare a readable PNG with strong contrast.","Place it in AppData/LocalLow/Hovgaard Games/Big Ambitions/CustomIcons.","Open the business in BizMan and enter logo customization.","Refresh the file list, select the image, and save.","If it does not appear, recheck format, save state, and restart the game."],caution:"Older posts disagree between 512×512 and 1024×1024. The best current image size is To be confirmed from the 1.0 prompt or default template; back up saves before changing any related files.",sources:["forum","guides"],deAnswer:"Lege eine PNG-Datei im Windows-Ordner CustomIcons ab und wähle sie anschließend in der Unternehmensanpassung von BizMan. Die genaue optimale Bildgröße muss in Version 1.0 noch geprüft werden." },
  { keyword:"big ambitions similar games",category:"alternatives",slug:"big-ambitions-similar-games",answer:"The most useful Big Ambitions alternatives depend on what you want to preserve: deep company management, open-world life simulation, hands-on shop operation, or office and employee systems. No single alternative reproduces every part of the game.",confirmed:"Steam recommendations and community discussions commonly compare Startup Company, Software Inc., Capitalism, SAELIG, The Guild, and retail-management simulations. Each comparison needs a feature-by-feature explanation because many business games lack direct character control or an open city.",steps:["Choose whether business depth or character life is the priority.","Check whether you want direct shop-floor work or abstract management.","Confirm employee, office, production, and logistics features on the candidate's Steam page.","Check the actual single-player or multiplayer tags.","Compare what the alternative omits as carefully as what it shares."],caution:"A community mention is not a guarantee of identical mechanics. Platform support, multiplayer, romance, and current availability should be verified on each candidate's official store page.",sources:["steam","guides"],deAnswer:"Die beste Alternative hängt davon ab, ob du Unternehmensführung, offene Lebenssimulation, aktive Ladenarbeit oder Personal- und Bürosysteme suchst. Kein einzelnes Spiel bildet alle Elemente von Big Ambitions ab." },
  { keyword:"big ambitions multiplayer alternatives",category:"alternatives",slug:"big-ambitions-multiplayer-alternatives",answer:"Big Ambitions is officially listed as single-player, so players who need co-op or competitive business play should choose a separately verified multiplayer alternative. An unofficial community multiplayer project is not the same as official online support.",confirmed:"The current Steam page marks Big Ambitions as Single-player. Community discussion mentions an unofficial Big Ambitions Online mod project whose developer says it is not affiliated with Hovgaard Games.",steps:["Decide whether you want co-op management or competitive economics.","Verify the multiplayer feature on the alternative game's Steam page.","Check player limits, hosting method, and whether progress is shared.","Separate native multiplayer from third-party mods.","Review current support and update history before buying for a group."],caution:"Do not describe the community multiplayer project as an official mode. Its compatibility, security, and current status are To be confirmed before use.",sources:["steam"],deAnswer:"Big Ambitions ist offiziell als Einzelspieler-Spiel gelistet. Für Koop oder wirtschaftlichen Wettbewerb brauchst du eine separat geprüfte Multiplayer-Alternative; ein Community-Mod ist keine offizielle Online-Funktion." },
  { keyword:"big ambitions romance alternatives",category:"alternatives",slug:"big-ambitions-romance-alternatives",answer:"Big Ambitions does not advertise a deep romance or partner system as a core feature. Players who want business management together with relationship progression should compare life simulations whose official descriptions clearly confirm romance.",confirmed:"Official Big Ambitions material emphasizes business, investment, real estate, health, and happiness rather than dating mechanics. A recommendation therefore needs separate ratings for business depth, life simulation, and actual relationship development.",steps:["Confirm that romance is a real progression system, not decorative dialogue.","Compare the candidate's business or shop-management depth.","Check how much direct character life simulation it includes.","Verify platform, current availability, and relationship restrictions.","Choose based on the balance of romance and management you actually want."],caution:"A game with NPC conversations or marriage decoration should not be presented as a full romance simulation. Candidate features must be checked on official store pages.",sources:["official","steam"],deAnswer:"Big Ambitions bewirbt kein tiefes Liebes- oder Partnersystem als Kernfunktion. Wer Beziehung und Unternehmensführung verbinden möchte, sollte Lebenssimulationen mit offiziell bestätigter Romanze vergleichen." },
  { keyword:"big ambitions 1.0 release date",category:"updates",slug:"big-ambitions-1-0-release-date",answer:"Big Ambitions version 1.0 released on August 28, 2026. The game first entered Steam Early Access on March 10, 2023, so the 2023 date should not be presented as the full-release date.",confirmed:"The Steam store and official project material distinguish the Early Access period from the 1.0 launch. Release coverage also describes new district or life content and changes to banking and management, but feature details should be read in the official launch announcement.",steps:["Use March 10, 2023 for the Early Access launch.","Use August 28, 2026 for the version-1.0 release.","Check Steam News for the final launch change list.","Separate launch features from later patches.","Do not reuse outdated pages that call 2023 the final release."],caution:"Any platform release beyond Windows and macOS on Steam is To be confirmed. A 1.0 date does not imply an announced console or mobile version.",sources:["official","steam","news"],deAnswer:"Big Ambitions 1.0 erschien am 28. August 2026. Der 10. März 2023 war der Start im Steam Early Access und darf nicht als Datum der Vollversion bezeichnet werden." },
  { keyword:"big ambitions next update",category:"updates",slug:"big-ambitions-next-update",answer:"The next Big Ambitions update has no confirmed date in the researched material. Treat only the official roadmap, Steam News, the developer website, or a direct developer announcement as confirmation.",confirmed:"Version 1.0 released on August 28, 2026, making older roadmap predictions especially easy to misread. A useful update page must separate already released work, confirmed plans without dates, and player suggestions.",steps:["Check the official roadmap first.","Compare it with the newest Steam News post.","Look for a date stated directly by Hovgaard Games.","Label undated plans separately from dated releases.","Replace the old next-update entry when a newer official announcement appears."],caution:"Community wish lists, mod features, and speculation are not official plans. Next release date: To be confirmed.",sources:["roadmap","news","official"],deAnswer:"Für das nächste Update von Big Ambitions ist im geprüften Material kein bestätigtes Datum genannt. Als Bestätigung gelten nur Roadmap, Steam-News, Entwicklerwebsite oder direkte Aussagen von Hovgaard Games." },
  { keyword:"big ambitions patch notes",category:"updates",slug:"big-ambitions-patch-notes",answer:"Use Big Ambitions Steam News and official developer posts as the factual patch-note record. Organize each version by release date, new features, balance changes, bug fixes, save compatibility, and known issues without mixing in community guesses.",confirmed:"Older Early Access notes remain useful history, but the default view should prioritize version 1.0 and later updates. Steam Community posts can reveal player impact, yet they should be labeled separately from the official change list.",steps:["Record the exact version and official release date.","Summarize features, balance, and fixes in separate groups.","Copy no claim that is absent from the official announcement.","Add save compatibility and known issues only when confirmed.","Link the original official post for context."],caution:"A reported player problem is not automatically an acknowledged known issue. Future patch content and dates remain To be confirmed until published officially.",sources:["news","official","steam"],deAnswer:"Die verlässliche Grundlage für Patch Notes sind Steam-News und offizielle Entwicklerbeiträge. Trenne Version, Datum, neue Funktionen, Balance, Fehlerbehebungen, Speicherkompatibilität und bekannte Probleme klar voneinander." },
  { keyword:"big ambitions ps5",category:"platforms",slug:"big-ambitions-ps5",answer:"There is currently no confirmed Big Ambitions PS5 version or official PlayStation Store listing. The verified release platforms are Windows and macOS through Steam, and no console date should be inferred from controller support or player requests.",confirmed:"The official website and Steam page provide the verified PC and Mac release information but no PS5 product page. Without an official PlayStation listing or developer announcement, price, pre-order, features, and release date remain unconfirmed.",steps:["Check the official Big Ambitions website.","Check Steam News and the public roadmap.","Look for a real PlayStation Store product page.","Require a direct developer announcement before publishing a date.","Ignore controller-layout evidence as proof of a console build."],caution:"PS5 version, price, pre-order, and release date: To be confirmed. Do not download or buy unofficial products claiming to be a console release.",sources:["official","steam","roadmap"],deAnswer:"Derzeit gibt es keine bestätigte PS5-Version und keinen offiziellen PlayStation-Store-Eintrag für Big Ambitions. Verifiziert sind Windows und macOS über Steam; ein Konsolentermin darf nicht vermutet werden." },
  { keyword:"big ambitions mobile",category:"platforms",slug:"big-ambitions-mobile",answer:"There is currently no official Big Ambitions mobile version for Android or iOS. The verified platforms are Windows and macOS on Steam, and remote streaming to a phone is not the same as a native mobile release.",confirmed:"Neither the official website nor the Steam store provides a formal Android or iOS product listing. Claims about mobile APK downloads therefore do not establish an official release.",steps:["Check Hovgaard Games and the official Big Ambitions website.","Require a verified App Store or Google Play listing.","Distinguish Steam remote streaming from a native app.","Avoid APK files distributed by unknown sites.","Wait for an official platform announcement before publishing a date."],caution:"Android version, iOS version, mobile price, and release date: To be confirmed. Unknown APK files may be unsafe and are not recommended.",sources:["official","steam"],deAnswer:"Eine offizielle Android- oder iOS-Version von Big Ambitions ist derzeit nicht bestätigt. Steam-Streaming auf ein Mobilgerät ist keine native mobile Veröffentlichung." },
  { keyword:"big ambitions mods",category:"mods",slug:"big-ambitions-mods",answer:"Use the Big Ambitions Steam Workshop for current mods and enable subscribed content through the game's supported menu flow. Check version compatibility, back up saves, record enabled items, and disable all mods first when diagnosing a crash.",confirmed:"The researched Steam Workshop material shows that Big Ambitions uses Workshop content for mods and building layouts. Mods and Blueprints are different: mods change or extend behavior, while Blueprints store reusable interiors and use an installation workflow.",steps:["Open the official Big Ambitions Steam Workshop.","Read the item description, required dependencies, and current version notes.","Subscribe and enable the mod from the game's menu.","Back up the save and test one change at a time.","After a crash, disable all mods and restore them individually."],caution:"Avoid unknown executable downloads and verify Workshop compatibility after game updates. A popular subscription count is not proof that a mod is safe for the current version.",sources:["workshop","steam","forum"],deAnswer:"Nutze den offiziellen Steam Workshop für Mods von Big Ambitions. Prüfe Version und Abhängigkeiten, sichere Spielstände, notiere aktive Mods und deaktiviere bei Abstürzen zuerst alle Erweiterungen." },
  { keyword:"big ambitions blueprints",category:"mods",slug:"big-ambitions-blueprints",answer:"Big Ambitions Blueprints save and reuse interior layouts for businesses, apartments, or warehouses. Create or save them through the Blueprint Creator or interior-design flow, then install a compatible layout through the correct in-game installation company.",confirmed:"Steam Workshop and community guides describe blueprints as layouts rather than code mods. A blueprint must match the property type, building code, and available size, and a Workshop subscription still needs to synchronize with the in-game library.",steps:["Create or save a layout from the supported blueprint interface.","Subscribe to a Workshop blueprint from a trusted listing.","Synchronize it with the in-game library.","Confirm property type, building code, and size compatibility.","Use the correct interior installation company to apply it."],caution:"Older layouts may depend on outdated game versions or mods. If a blueprint does not appear, check synchronization, compatibility, installer choice, and dependencies before changing the save.",sources:["workshop","guides"],deAnswer:"Blueprints speichern und wiederverwenden Innenraumlayouts für Geschäfte, Wohnungen oder Lager. Sie müssen zu Immobilientyp, Gebäudecode und Größe passen und über den richtigen Einrichtungsbetrieb installiert werden." },
  { keyword:"big ambitions review",category:"reviews",slug:"big-ambitions-review",answer:"Big Ambitions is best suited to players who enjoy growing from hands-on work into systems, staffing, logistics, investment, and executive management. Its appeal is the visible business journey; common reservations concern repetition, later pacing, employee management, and balance.",confirmed:"The Steam page showed a Very Positive English review summary in the research snapshot dated August 31, 2026. Exact review counts and percentages change continuously, so this page focuses on recurring themes rather than freezing those numbers as permanent facts.",steps:["Judge the business and automation depth first.","Decide whether direct city movement adds immersion or repetition for you.","Consider how much employee and logistics management you want.","Read current performance and patch reports for your hardware.","Compare the game with business simulations, not action open worlds."],caution:"Review totals and recent percentages are time-sensitive and should be checked live on Steam. This independent guide does not convert a changing score into a permanent rating.",sources:["steam","official"],deAnswer:"Big Ambitions passt besonders zu Spielern, die den Weg von eigener Arbeit zu Personal, Logistik, Investments und Unternehmensführung mögen. Kritik betrifft häufig Wiederholungen, spätes Tempo, Personalverwaltung und Balance." },
  { keyword:"big ambitions crashes",category:"troubleshooting",slug:"big-ambitions-crashes",answer:"For Big Ambitions crashes, check system requirements, update the operating system and graphics driver, verify Steam files, disable every mod, and test a clean launch before changing saves or configuration. Back up data before clearing anything.",confirmed:"Public reports frequently mention startup failures or long shader-compilation stages. Community-tested launch options can reduce quality and use a low-resolution window, but that is a troubleshooting experiment rather than an official guaranteed fix.",steps:["Compare the computer with the current Steam minimum requirements.","Update the graphics driver and operating system.","Use Steam to verify installed game files.","Disable all mods and test a clean or backed-up save.","Try low-quality windowed launch options only as a temporary diagnostic.","Collect logs, version, hardware, and reproduction steps for official support."],caution:"The researched community launch string is -screen-quality Low -screen-fullscreen 0 -screen-width 1024 -screen-height 768. Back up saves first; do not delete configuration or caches without a recoverable copy.",sources:["steam","forum"],deAnswer:"Bei Abstürzen prüfst du zuerst Anforderungen, System und Grafiktreiber, verifizierst Steam-Dateien und deaktivierst alle Mods. Teste sauber und sichere Daten, bevor du Konfigurationen oder Caches veränderst." },
  { keyword:"big ambitions water cooler",category:"guides",slug:"big-ambitions-water-cooler",answer:"A current, officially documented Big Ambitions water-cooler location, seller, price, or business requirement could not be confirmed from the researched sources. Check the exact item name in F1 help and the live BizMan requirement before buying a similarly named furnishing.",confirmed:"The official Steam description confirms that businesses use placeable furnishings and equipment, but it does not identify a Water Cooler or publish a permanent seller and price. Search results also mix this phrase with unrelated games, so those answers must not be imported into a Big Ambitions guide.",steps:["Read the exact unmet item name in BizMan.","Search F1 help for Water Cooler and nearby terms such as drinks or office equipment.","Use the item entry to identify any current seller.","Check the live store inventory rather than an old screenshot.","Place the item and confirm whether BizMan marks the requirement as satisfied."],caution:"Water Cooler availability, seller, price, size, and business effect are To be confirmed in the current build. Do not treat information about the water cooler in another game as evidence for Big Ambitions.",sources:["official","steam","forum"],deAnswer:"Für einen Wasserspender in Big Ambitions konnten weder Händler noch Preis, Standort oder Geschäftseffekt aktuell offiziell bestätigt werden. Prüfe den exakten Gegenstand in der F1-Hilfe und die Anforderung in BizMan." },
  { keyword:"big ambitions ai music",category:"media",slug:"big-ambitions-ai-music",answer:"There is no verified official statement in the researched material confirming that Big Ambitions uses AI-generated music. An official community response says the radio advertising jingles are original and the in-game music is licensed, which does not by itself establish how every track was produced.",confirmed:"A Hovgaard Games community representative stated that the radio ad jingles are original and all music in the game is licensed for the game and for streaming. The researched official store and developer pages do not label the soundtrack as AI-generated.",steps:["Separate music licensing from the method used to create a track.","Check the current credits and official soundtrack information.","Look for a direct statement from Hovgaard Games or the credited artist.","Treat social posts and detection tools as leads rather than proof.","Update the conclusion only when a primary source identifies the production method."],caution:"Whether any specific track used generative AI is To be confirmed. A licensed track can be human-made or produced with different tools, so licensing status cannot prove or disprove AI use.",sources:["official","steam","forum"],deAnswer:"Es gibt in den geprüften Quellen keine bestätigte offizielle Aussage, dass Big Ambitions KI-generierte Musik verwendet. Bestätigt sind originäre Radio-Jingles und für Spiel sowie Streaming lizenzierte Musik." },
  { keyword:"big ambitions music",category:"media",slug:"big-ambitions-music",answer:"Big Ambitions includes licensed in-game music and original radio advertising jingles, and it supports local MP3 files through a separate custom radio station. Add MP3 files directly to the configured music folder, then select the custom station on an in-game radio.",confirmed:"An official community response says the music is licensed for use in the game and streaming, although automated copyright flags may still occur. Developer replies also confirm that local MP3 tracks play on their own station and that the station appears after compatible files are added.",steps:["Open Options and then Audio to find the local-music folder setting.","Place MP3 files directly in the selected folder without relying on subfolders.","Return to the game and turn on a radio or compatible speaker.","Switch to the local or custom station rather than the default soundtrack station.","If it is missing, verify file type and folder placement before reporting a bug."],caution:"The complete current soundtrack list and publisher ownership for every individual track are To be confirmed. Streaming is permitted according to the official community response, but automated claims may still need to be disputed with the rights holder.",sources:["forum","steam"],deAnswer:"Big Ambitions enthält lizenzierte Spielmusik und eigene Radio-Werbejingles. Eigene MP3-Dateien können über einen separaten lokalen Radiosender abgespielt werden, nachdem sie direkt im konfigurierten Musikordner liegen." },
  { keyword:"big ambitions life sim game",category:"alternatives",slug:"big-ambitions-life-sim-game",answer:"Big Ambitions is a business simulation with life-simulation systems, not a pure everyday-life simulator. The player manages sleep, food, health, happiness, housing, travel, and purchases while building shops, offices, logistics, property, and investments across New York.",confirmed:"The official Steam description calls Big Ambitions a role-playing business simulation and explicitly says the character must interact with the world to survive and succeed. Steam also lists Life Sim among its popular user-defined tags while the core description remains focused on entrepreneurship.",steps:["Expect business growth to remain the main progression loop.","Manage personal needs because they affect the character operating that business.","Use apartments, transport, stores, and city services as functional systems.","Compare it with pure life sims based on relationships and domestic depth separately.","Use the official feature list before assuming a particular life-sim mechanic exists."],caution:"The life-sim label does not confirm deep romance, family, aging, multiplayer, or every feature associated with other life simulators. Those mechanics must be verified individually.",sources:["official","steam"],deAnswer:"Big Ambitions ist eine Wirtschaftssimulation mit Lebenssimulations-Systemen, keine reine Alltagssimulation. Schlaf, Nahrung, Gesundheit, Glück, Wohnen und Wege begleiten den Aufbau von Unternehmen, Logistik und Investments." },
  { keyword:"big ambitions uniform",category:"guides",slug:"big-ambitions-uniform",answer:"Big Ambitions supports employee uniforms, but the exact current assignment controls and available clothing colors should be checked in the live employee-management interface. Older official-forum replies say uniforms were implemented in Beta 8 and later clothing choices expanded during Early Access.",confirmed:"The official community forum marks the original staff-uniform suggestion as implemented in Beta 8. A later implemented-suggestions thread reports additional clothing and uniform options in the EA 0.8 experimental build, while players also documented limits in matching colors across clothing types.",steps:["Open BizMan and select the relevant business or employee group.","Look for the current uniform or clothing assignment control.","Choose only options available to that employee model and role.","Check the result during an active shift inside the business.","Revisit the menu after updates because colors and clothing choices can change."],caution:"The exact version-1.0 menu path, full clothing list, color compatibility, and whether a logo can appear on uniforms are To be confirmed. The old suggestion that a store logo might be added was an idea, not proof of that feature.",sources:["forum","steam"],deAnswer:"Big Ambitions unterstützt Mitarbeiteruniformen. Den aktuellen Menüpfad und die verfügbaren Kleidungsfarben solltest du direkt in der Mitarbeiterverwaltung prüfen; ältere offizielle Forenbeiträge bestätigen die Einführung und spätere Erweiterungen." },
  { keyword:"big ambitions multiplayer",category:"platforms",slug:"big-ambitions-multiplayer",answer:"Big Ambitions does not currently offer official multiplayer or co-op; Steam lists the game as single-player. Older developer comments discussed multiplayer as a possible post-release idea, but they are not a release announcement, roadmap commitment, or confirmed date.",confirmed:"The current Steam feature list identifies Single-player and does not list online co-op, LAN co-op, or multiplayer. In the official community forum, the developer described multiplayer as a major rebuild and acknowledged player interest without confirming implementation.",steps:["Check the current Steam feature list for any platform-status change.","Review the official roadmap and newest Steam News posts.","Require a direct Hovgaard Games announcement before treating multiplayer as planned.","Distinguish official support from third-party community projects.","Do not buy or download an unofficial tool expecting native co-op compatibility."],caution:"Official multiplayer, co-op, player count, networking model, and release date are To be confirmed. Past statements about what might happen after release are not a promise that the feature will ship.",sources:["steam","roadmap","forum"],deAnswer:"Big Ambitions bietet derzeit keinen offiziellen Mehrspieler- oder Koop-Modus; Steam führt das Spiel als Einzelspieler. Ältere Entwicklerkommentare waren Überlegungen und keine bestätigte Ankündigung oder Terminplanung." },
];

function makeTitle(keyword: string): string {
  let title = `${keyword} — Verified Guide`;
  if (title.length < 40) title += " for Players";
  if (title.length > 60) title = `${keyword} Guide`;
  return title;
}

function makeFrenchTitle(keyword: string): string {
  let title = `${keyword} — Guide vérifié`;
  if (title.length < 40) title = `${keyword} — Guide complet et vérifié`;
  if (title.length > 60) title = `${keyword} — Guide`;
  return title;
}

function makeDescription(keyword: string, answer: string): string {
  const base = `${keyword}: ${answer} This guide uses verified sources and marks unconfirmed details clearly.`;
  if (base.length <= 160 && base.length >= 140) return base;
  if (base.length < 140) return `${base.slice(0,-1)} for current players.`;
  const sliced = base.slice(0, 159);
  const boundary = sliced.lastIndexOf(" ");
  return `${sliced.slice(0, boundary)}.`;
}

function englishSections(item: Research): ArticleSection[] {
  const steps = item.steps;
  return [
    { heading:"What the research confirms", paragraphs:[item.confirmed,`This matters because the phrase “${item.keyword}” often surfaces a mixture of official descriptions, older Early Access instructions, current community experience, and generic search results. The reliable answer keeps those layers separate and gives priority to the current game, Steam, the developer site, and in-game tools.`] },
    { heading:"The practical way to handle it", paragraphs:[`Start with the current interface rather than a memorized location or number. Big Ambitions changes as updates adjust objectives, items, balance, and navigation, so a repeatable verification method is more useful than a brittle shortcut.`, `Use the following order as a working checklist. Each step is based on the collected material, while exact prices, times, addresses, and version-specific labels should be read from the live game.`], bullets:steps },
    { heading:"How to verify the current version", paragraphs:[`Check F1 help for the exact object or mechanic, BizMan for business requirements and status, Market Insider for district demand and competition, and the map for current sellers or services. For update and platform questions, use Steam News, the official roadmap, and Hovgaard Games announcements.`, `If an older video or discussion disagrees with the current interface, the current game wins. Record the version and date when sharing the answer so another player can tell whether the instruction still applies.`] },
    { heading:"What not to assume", paragraphs:[item.caution,`Do not turn community preference into an official rule, and do not turn an unverified value into a precise claim. A number that changes with a patch or save can make an otherwise useful guide misleading, which is why uncertain details are marked To be confirmed.`] },
    { heading:"A decision framework that stays useful", paragraphs:[`Separate the immediate player goal from the larger business system. Ask what must be unlocked or purchased, what ongoing cost or dependency it creates, how it affects staffing and logistics, and whether the same result can be reached with less risk.`, `Keep a cash buffer and a backup before testing changes that affect saves, mods, layouts, or configuration. When the topic involves another game or platform, verify the feature on its official store page rather than relying on a list or short video title.`] },
    { heading:"Read source claims in the right order", paragraphs:[`Begin with the official Steam page, developer website, roadmap, Steam News, and the current in-game interface. These sources establish supported platforms, release status, official features, and the words the game currently uses. The official forum can add developer clarification, while Steam guides, Reddit discussions, and videos are better for identifying the practical trouble players encounter.`, `A community post can be accurate for one patch and still be wrong today. Look at its date, note whether it describes Early Access or version 1.0, and check whether the author is reporting personal experience or quoting an official source. When no current primary source confirms the claim, the honest status is To be confirmed.`] },
    { heading:"Common mistakes to avoid", paragraphs:[`The most common research mistake is copying a precise answer because it appears repeatedly. Repetition can come from several sites copying the same outdated post, so it does not replace confirmation. Another mistake is treating a feature request, a mod, or an interface label found in game files as proof of an announced official feature.`, `For gameplay decisions, avoid spending every available dollar just to follow an optimization tip. Rent, wages, inventory, logistics, personal needs, and unexpected changes still need working capital. For technical changes, preserve the original save or configuration so a failed test can be reversed without losing progress.`] },
    { heading:"When to recheck this page", paragraphs:[`Recheck the answer after a major patch, a change to Steam platform tags, a new roadmap entry, or an official announcement from Hovgaard Games. Also recheck whenever F1 help, BizMan, Market Insider, the map, or the main-menu Workshop flow no longer matches the wording here.`, `A useful guide records the date of its last review and replaces obsolete guidance instead of hiding it beneath newer guesses. This page was checked against the collected research on August 31, 2026; facts that depend on a later build should be verified again before use.`] },
    { heading:"Plan a safe in-game test", paragraphs:[`When the answer can be verified inside a save, test it in a controlled way. Write down the current game version, preserve a backup, keep enough money to reverse the decision, and change only one relevant variable at a time. That makes it possible to tell whether a result came from the item, business choice, mod, blueprint, launch option, or a separate change in the save.`, `After the test, compare the result with BizMan, Market Insider, F1 help, the map, or the applicable menu. A visible status change is stronger evidence than an assumption based on appearance. If the result cannot be repeated, describe it as a player report rather than converting it into a guaranteed instruction.`] },
    { heading:"Share the answer without overstating it", paragraphs:[`A strong community answer says what was tested, on which version, and which part came from an official source. It also explains the boundary of the claim: a business can work well in one district without being the universal best, and a workaround can help one graphics setup without being an official crash fix.`, `Avoid removing the uncertainty label merely to make the answer sound confident. Clear limits help other players decide whether to spend money, alter a save, install content, or wait for an announcement. They also make the page easier to update when a later patch supplies the missing fact.`] },
    { heading:"Bottom line", paragraphs:[item.answer,`The answer is intentionally conservative: it uses what the collected sources actually support and leaves version-sensitive details open when they cannot be confirmed. Recheck official or in-game information after a patch, and treat unsupported dates, prices, codes, and compatibility claims as To be confirmed.`] },
  ];
}

function germanSections(item: Research): ArticleSection[] {
  return [
    { heading:"Direkte Antwort", paragraphs:[item.deAnswer,"Diese Seite trennt bestätigte Angaben von älteren Community-Berichten. Versionsabhängige Werte, Orte und Termine werden nicht erfunden, sondern als Noch zu bestätigen markiert."] },
    { heading:"Was die Quellen belegen", paragraphs:["Offizielle Website, Steam, Entwicklerforum und die aktuellen Spielhilfen haben Vorrang. Beiträge aus Community und Videos erklären typische Fragen, ersetzen aber keine offizielle Bestätigung.","Prüfe bei widersprüchlichen Angaben immer die aktuelle Version, F1-Hilfe, BizMan, Market Insider oder die neueste offizielle Ankündigung."] },
    { heading:"Empfohlene Reihenfolge", paragraphs:["Arbeite die Schritte in dieser Reihenfolge ab und kontrolliere jeden Status im Spiel. Preise, Öffnungszeiten, Adressen und Balancewerte können sich mit Updates ändern."], bullets:item.steps },
    { heading:"Noch zu bestätigen", paragraphs:[item.caution,"Unsichere Angaben bleiben ausdrücklich offen. Dadurch entstehen keine erfundenen Zahlen, Figuren, Codes oder Veröffentlichungstermine."] },
    { heading:"Fazit", paragraphs:[item.deAnswer,"Kontrolliere die offiziellen Quellen nach jedem größeren Patch erneut und behandle ältere Anleitungen als Orientierung, nicht als unveränderliche Regel."] },
  ];
}

function frenchSections(item: Research): ArticleSection[] {
  const content = frenchResearch[item.slug];
  return [
    { heading:"Réponse directe", paragraphs:[content.answer,"Cette page distingue les faits confirmés des anciens témoignages de la communauté. Les valeurs, lieux et dates dépendant d’une version restent clairement indiqués comme étant à confirmer."] },
    { heading:"Ce que confirment les sources", paragraphs:[content.confirmed,"Le site officiel, Steam, le forum du développeur et les aides actuelles du jeu sont prioritaires. Les publications communautaires et les vidéos expliquent les difficultés habituelles, mais ne remplacent pas une confirmation officielle."] },
    { heading:"Procédure recommandée", paragraphs:["Suivez les étapes dans cet ordre et contrôlez chaque état directement dans le jeu. Les prix, horaires, adresses, libellés et valeurs d’équilibrage peuvent changer après une mise à jour."], bullets:content.steps },
    { heading:"Vérifier la version actuelle", paragraphs:["Consultez l’aide F1 pour l’objet ou le mécanisme exact, BizMan pour les besoins de l’entreprise, Market Insider pour la demande et la concurrence, et la carte pour les vendeurs actuels. Pour les mises à jour et les plateformes, privilégiez les actualités Steam, la feuille de route et les annonces de Hovgaard Games.","Si une ancienne vidéo contredit l’interface actuelle, fiez-vous au jeu actuel. Notez la version et la date lorsque vous partagez une solution afin que les autres joueurs sachent si elle s’applique encore."] },
    { heading:"Informations à confirmer", paragraphs:[content.caution,"Les éléments incertains restent explicitement ouverts. Cette méthode évite d’inventer des chiffres, des personnages, des codes, des prix ou des dates de sortie."] },
    { heading:"Éviter les erreurs fréquentes", paragraphs:["Ne transformez pas une préférence communautaire en règle officielle et ne présentez pas une valeur non vérifiée comme un chiffre précis. Une information peut être répétée par plusieurs sites simplement parce qu’ils copient tous une ancienne publication.","Pour les décisions de gestion, gardez toujours une réserve pour le loyer, les salaires, le stock, la logistique et les besoins personnels. Pour les modifications techniques, conservez une sauvegarde ou une copie de la configuration afin de pouvoir revenir en arrière."] },
    { heading:"Quand vérifier de nouveau", paragraphs:["Contrôlez cette réponse après une mise à jour importante, un changement des plateformes affichées sur Steam, une nouvelle étape de la feuille de route ou une annonce officielle. Faites de même si l’aide F1, BizMan, Market Insider, la carte ou le menu Workshop ne correspondent plus à cette page.","Un guide fiable indique la date de sa dernière vérification et remplace les anciennes consignes au lieu de les masquer sous de nouvelles suppositions. Les faits dépendant d’une version ultérieure doivent être vérifiés avant utilisation."] },
    { heading:"Tester sans risquer sa partie", paragraphs:["Lorsque la réponse peut être contrôlée dans une sauvegarde, réalisez un test limité. Notez la version, créez une copie, gardez assez d’argent pour annuler votre décision et ne changez qu’une seule variable à la fois.","Comparez ensuite le résultat avec BizMan, Market Insider, l’aide F1, la carte ou le menu concerné. Un changement d’état visible constitue une meilleure preuve qu’une simple impression ; si le résultat n’est pas reproductible, présentez-le comme un témoignage de joueur."] },
    { heading:"Sources et niveau de confiance", paragraphs:["Commencez par la page Steam officielle, le site du développeur, la feuille de route, les actualités Steam et l’interface actuelle. Le forum officiel peut fournir des précisions, tandis que les guides Steam, les discussions et les vidéos servent surtout à repérer les problèmes pratiques rencontrés par les joueurs.","Une publication communautaire peut être juste pour une ancienne version et fausse aujourd’hui. Vérifiez sa date, distinguez l’accès anticipé de la version 1.0 et regardez si l’auteur cite une source officielle ou seulement son expérience."] },
    { heading:"Conclusion", paragraphs:[content.answer,"Cette réponse reste volontairement prudente : elle reprend uniquement ce que les sources étudiées permettent d’affirmer. Après une mise à jour, vérifiez de nouveau les données officielles et considérez les dates, prix, codes et compatibilités non documentés comme étant à confirmer."] },
  ];
}

function createArticle(item: Research, locale: Locale): Article {
  const french = frenchResearch[item.slug];
  const answer = locale === "en" ? item.answer : locale === "de" ? item.deAnswer : french.answer;
  const keyword = locale === "fr" ? frenchKeywords[item.slug] : item.keyword;
  return {
    locale,
    keyword,
    category:item.category,
    slug:item.slug,
    title: locale === "en" ? makeTitle(item.keyword) : locale === "de" ? `${item.keyword} — Verifizierter Guide` : makeFrenchTitle(keyword),
    description: makeDescription(keyword,answer),
    summary:answer,
    answer,
    updated:locale === "fr" ? "31 août 2026" : "August 31, 2026",
    sections:locale === "en" ? englishSections(item) : locale === "de" ? germanSections(item) : frenchSections(item),
    sources:item.sources.map((key)=>({label:locale === "fr" ? (key === "official" ? "Site officiel de Big Ambitions" : key === "steam" ? "Big Ambitions sur Steam" : key === "news" ? "Actualités Steam officielles" : key === "roadmap" ? "Feuille de route officielle" : key === "workshop" ? "Atelier Steam" : key === "forum" ? "Forum officiel" : "Guides de la communauté Steam") : (key === "official" ? "Official Big Ambitions website" : key === "steam" ? "Big Ambitions on Steam" : key === "news" ? "Official Steam News" : key === "roadmap" ? "Official roadmap" : key === "workshop" ? "Steam Workshop" : key === "forum" ? "Official forum" : "Steam Community Guides"),href:links[key]})),
  };
}

const articles: Record<Locale, Article[]> = {
  en: research.map((item)=>createArticle(item,"en")),
  de: research.map((item)=>createArticle(item,"de")),
  fr: research.map((item)=>createArticle(item,"fr")),
};

export function getArticles(locale: Locale): Article[] { return articles[locale]; }
export function getArticle(locale: Locale, slug: string): Article | undefined { return articles[locale].find((article)=>article.slug === slug); }
export function getCategories(locale: Locale): string[] { return [...new Set(articles[locale].map((article)=>article.category))]; }
